const contents = {
    original: `<h1 style="text-align: center">Hey there 👋</h1><p>This is a <em>basic</em> example of <code>mui-tiptap</code>, which combines <a target="_blank" rel="noopener noreferrer nofollow" href="https://tiptap.dev/">Tiptap</a> with customizable <a target="_blank" rel="noopener noreferrer nofollow" href="https://mui.com/">MUI (Material-UI)</a> styles, plus a suite of additional components and extensions! Sure, there are <strong>all <em>kinds</em> of <s>text</s> <u>formatting</u> options</strong> you’d probably expect from a rich text editor. But wait until you see the lists:</p><ul><li><p>That’s a bullet list with one …</p></li><li><p>… or two list items.</p></li></ul><p>Isn’t that great? And all of that is editable. But wait, there’s more. Let’s try a code block:</p><pre><code class="language-css">body {\n  display: none;\n}</code></pre><p></p><p>That’s only the tip of the iceberg. Feel free to add and resize images:</p><img height="auto" src="http://placekitten.com/g/500" alt="wat" width="257" style="aspect-ratio: 1 / 1"><p></p><p>Organize information in tables:</p><table><tbody><tr><th colspan="1" rowspan="1"><p>Name</p></th><th colspan="1" rowspan="1"><p>Role</p></th><th colspan="1" rowspan="1"><p>Team</p></th></tr><tr><td colspan="1" rowspan="1"><p>Alice</p></td><td colspan="1" rowspan="1"><p>PM</p></td><td colspan="1" rowspan="1"><p>Internal tools</p></td></tr><tr><td colspan="1" rowspan="1"><p>Bob</p></td><td colspan="1" rowspan="1"><p>Software</p></td><td colspan="1" rowspan="1"><p>Infrastructure</p></td></tr></tbody></table><p></p><p>Or write down your groceries:</p><ul data-type="taskList"><li data-checked="true" data-type="taskItem"><label><input type="checkbox" checked="checked"><span></span></label><div><p>Milk</p></div></li><li data-checked="false" data-type="taskItem"><label><input type="checkbox"><span></span></label><div><p>Eggs</p></div></li><li data-checked="false" data-type="taskItem"><label><input type="checkbox"><span></span></label><div><p>Sriracha</p></div></li></ul><blockquote><p>Wow, that’s amazing. Good work! 👏 <br>— Mom</p></blockquote><p>Give it a try and click around!</p>`
};

export const content = contents.original;

// <w:p w:rsidR="00354F54" w:rsidRDefault="00354F54" w:rsidP="00354F54" class="CAP">
// <w:pPr>
//     <w:pStyle w:val="CAP" />
// </w:pPr>
// <w:r>
//     <w:rPr><w:i value="1"></w:i></w:rPr>
//     <w:t>Figure 1.1.</w:t>
// </w:r>
// <w:r>
//     <w:t>A bar sign under Bologna’s famous porticos. Note the “T” in the back advertising that this
//         establishment also sells tobacco products. (Photograph by author)</w:t>
    
// </w:r>
// </w:p>


// export const content =  `<div name="w:document" xmlns-wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns-cx="http://schemas.microsoft.com/office/drawing/2014/chartex" xmlns-cx1="http://schemas.microsoft.com/office/drawing/2015/9/8/chartex" xmlns-cx2="http://schemas.microsoft.com/office/drawing/2015/10/21/chartex" xmlns-cx3="http://schemas.microsoft.com/office/drawing/2016/5/9/chartex" xmlns-cx4="http://schemas.microsoft.com/office/drawing/2016/5/10/chartex" xmlns-cx5="http://schemas.microsoft.com/office/drawing/2016/5/11/chartex" xmlns-cx6="http://schemas.microsoft.com/office/drawing/2016/5/12/chartex" xmlns-cx7="http://schemas.microsoft.com/office/drawing/2016/5/13/chartex" xmlns-cx8="http://schemas.microsoft.com/office/drawing/2016/5/14/chartex" xmlns-mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns-aink="http://schemas.microsoft.com/office/drawing/2016/ink" xmlns-am3d="http://schemas.microsoft.com/office/drawing/2017/model3d" xmlns-o="urn:schemas-microsoft-com:office:office" xmlns-r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns-m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns-v="urn:schemas-microsoft-com:vml" xmlns-wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns-wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns-w10="urn:schemas-microsoft-com:office:word" xmlns-w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns-w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns-w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns-w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid" xmlns-w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex" xmlns-wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns-wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns-wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns-wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc-Ignorable="w14 w15 w16se w16cid wp14"><div name="w:body"><p name="w:p" w-rsidR="00354F54" w-rsidRDefault="00354F54" w-rsidP="00354F54" class="CAP"><span name="w:pPr"><span name="w:pStyle" w-val="CAP"/></span><span name="w:r"><span name="w:t">Figure 1.1. A bar sign under Bologna’s famous porticos. Note the “T” in the back advertising that this establishment also sells tobacco products. (Photograph by author)</span></span></p>
//     <p name="w:p" w-rsidR="00354F54" w-rsidRDefault="00354F54" w-rsidP="00354F54" class="CAP"><span name="w:pPr"><span name="w:pStyle" w-val="CAP"/></span><span name="w:r"><span name="w:t">Figure 3.1. A typical scene from a peripheral neighborhood bar managed by Chinese families: an elderly pensioner reads local newspapers after the early morning rush. (Photograph by author)</span></span></p>
//     <p name="w:p" w-rsidR="00354F54" w-rsidRDefault="00354F54" w-rsidP="00354F54" class="CAP"><span name="w:pPr"><span name="w:pStyle" w-val="CAP"/></span><span name="w:r"><span name="w:t">Figure 3.2. A typical bar for passers-by in B</span></span><span name="w:bookmarkStart" w-id="0" w-name="_GoBack"/><span name="w:bookmarkEnd" w-id="0"/><span name="w:r"><span name="w:t">ologna’s historical center. Bars like this usually provide more options in terms of food and drinks to cater to a larger flow of clientele than a neighborhood bar. The owner of this bar is also Chinese. (Photograph by author)</span></span></p>
//     <p name="w:p" w-rsidR="00354F54" w-rsidRDefault="00354F54" w-rsidP="00354F54" class="CAP"><span name="w:pPr"><span name="w:pStyle" w-val="CAP"/></span><span name="w:r"><span name="w:t" xml-space="preserve">Figure 3.3. An old peg letter board listing drinks and prices next to the espresso coffee machine in </span></span><span name="w:proofErr" w-type="spellStart"/><span name="w:r"><span name="w:t">Lanlan’s</span></span><span name="w:proofErr" w-type="spellEnd"/><span name="w:r"><span name="w:t" xml-space="preserve"> family-run bar. (Photograph by author)</span></span></p>
//     <p name="w:p" w-rsidR="00354F54" w-rsidRDefault="00354F54" w-rsidP="00354F54" class="CAP"><span name="w:pPr"><span name="w:pStyle" w-val="CAP"/></span><span name="w:r"><span name="w:t" xml-space="preserve">Figure 3.4. Old and new games in </span></span><span name="w:proofErr" w-type="spellStart"/><span name="w:r"><span name="w:t">Lanlan’s</span></span><span name="w:proofErr" w-type="spellEnd"/><span name="w:r"><span name="w:t" xml-space="preserve"> family-run bar. For many older patrons, slot machines have replaced billiards as the preferred game of choice. (Photograph by author)</span></span></p>
//     <p name="w:p" w-rsidR="00354F54" w-rsidRDefault="00354F54" w-rsidP="00354F54" class="CAP"><span name="w:pPr"><span name="w:pStyle" w-val="CAP"/></span><span name="w:r"><span name="w:t" xml-space="preserve">Figure 3.5. A display of winning Italian </span></span><span name="w:proofErr" w-type="spellStart"/><span name="w:r" class="I"><span name="w:rPr"><span name="w:rStyle" w-val="I"/></span><span name="w:t">gratta</span></span><span name="w:proofErr" w-type="spellEnd"/><span name="w:r" class="I"><span name="w:rPr"><span name="w:rStyle" w-val="I"/></span><span name="w:t" xml-space="preserve"> e </span></span><span name="w:proofErr" w-type="spellStart"/><span name="w:r" class="I"><span name="w:rPr"><span name="w:rStyle" w-val="I"/></span><span name="w:t">vinci</span></span><span name="w:proofErr" w-type="spellEnd"/><span name="w:r"><span name="w:t" xml-space="preserve"> cards hanging above the bar counter. This is another popular gambling game in addition to slot machines. (Photograph by author)</span></span></p>
//     <p name="w:p" w-rsidR="00354F54" w-rsidRDefault="00354F54" w-rsidP="0041204E" class="CAP"><span name="w:pPr"><span name="w:pStyle" w-val="CAP"/></span><span name="w:r"><span name="w:t">Figure 4.1. Inside a coffee bar in a residential neighborhood. The Chinese owner told me that they have maintained the interior décor and spatial arrangement of this taste community as it was before. (Photograph by author)</span></span></p>
//     <p name="w:p" w-rsidR="00A705FB" w-rsidRPr="00EB4C92" w-rsidRDefault="00354F54" w-rsidP="0041204E" class="CAP"><span name="w:pPr"><span name="w:pStyle" w-val="CAP"/></span><span name="w:r"><span name="w:t">Figure 4.2. My first “successful” cappuccino with a heart-shaped latte art that received the approval from my barista teacher and compliments from some of the regular patrons who had witnessed my efforts.</span></span></p><span name="w:sectPr" w-rsidR="00A705FB" w-rsidRPr="00EB4C92"><span name="w:pgSz" w-w="12240" w-h="15840"/><span name="w:pgMar" w-top="1440" w-right="1440" w-bottom="1440" w-left="1440" w-header="720" w-footer="720" w-gutter="0"/><span name="w:cols" w-space="720"/><span name="w:docGrid" w-linePitch="360"/></span></div></div>
    
    
    
//     <div name="w:footnotes" xmlns-wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns-cx="http://schemas.microsoft.com/office/drawing/2014/chartex" xmlns-cx1="http://schemas.microsoft.com/office/drawing/2015/9/8/chartex" xmlns-cx2="http://schemas.microsoft.com/office/drawing/2015/10/21/chartex" xmlns-cx3="http://schemas.microsoft.com/office/drawing/2016/5/9/chartex" xmlns-cx4="http://schemas.microsoft.com/office/drawing/2016/5/10/chartex" xmlns-cx5="http://schemas.microsoft.com/office/drawing/2016/5/11/chartex" xmlns-cx6="http://schemas.microsoft.com/office/drawing/2016/5/12/chartex" xmlns-cx7="http://schemas.microsoft.com/office/drawing/2016/5/13/chartex" xmlns-cx8="http://schemas.microsoft.com/office/drawing/2016/5/14/chartex" xmlns-mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns-aink="http://schemas.microsoft.com/office/drawing/2016/ink" xmlns-am3d="http://schemas.microsoft.com/office/drawing/2017/model3d" xmlns-o="urn:schemas-microsoft-com:office:office" xmlns-r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns-m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns-v="urn:schemas-microsoft-com:vml" xmlns-wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns-wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns-w10="urn:schemas-microsoft-com:office:word" xmlns-w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns-w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns-w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns-w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid" xmlns-w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex" xmlns-wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns-wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns-wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns-wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc-Ignorable="w14 w15 w16se w16cid wp14"><div name="w:footnote" w-type="separator" w-id="-1"><p name="w:p" w-rsidR="005D5C1F" w-rsidRDefault="005D5C1F"><span name="w:r"><span name="w:separator"/></span></p></div><div name="w:footnote" w-type="continuationSeparator" w-id="0"><p name="w:p" w-rsidR="005D5C1F" w-rsidRDefault="005D5C1F"><span name="w:r"><span name="w:continuationSeparator"/></span></p></div></div>
    
    
    
//     <div name="w:endnotes" xmlns-wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns-cx="http://schemas.microsoft.com/office/drawing/2014/chartex" xmlns-cx1="http://schemas.microsoft.com/office/drawing/2015/9/8/chartex" xmlns-cx2="http://schemas.microsoft.com/office/drawing/2015/10/21/chartex" xmlns-cx3="http://schemas.microsoft.com/office/drawing/2016/5/9/chartex" xmlns-cx4="http://schemas.microsoft.com/office/drawing/2016/5/10/chartex" xmlns-cx5="http://schemas.microsoft.com/office/drawing/2016/5/11/chartex" xmlns-cx6="http://schemas.microsoft.com/office/drawing/2016/5/12/chartex" xmlns-cx7="http://schemas.microsoft.com/office/drawing/2016/5/13/chartex" xmlns-cx8="http://schemas.microsoft.com/office/drawing/2016/5/14/chartex" xmlns-mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns-aink="http://schemas.microsoft.com/office/drawing/2016/ink" xmlns-am3d="http://schemas.microsoft.com/office/drawing/2017/model3d" xmlns-o="urn:schemas-microsoft-com:office:office" xmlns-r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns-m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns-v="urn:schemas-microsoft-com:vml" xmlns-wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns-wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns-w10="urn:schemas-microsoft-com:office:word" xmlns-w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns-w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns-w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns-w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid" xmlns-w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex" xmlns-wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns-wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns-wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns-wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc-Ignorable="w14 w15 w16se w16cid wp14"><div name="w:endnote" w-type="separator" w-id="-1"><p name="w:p" w-rsidR="005D5C1F" w-rsidRDefault="005D5C1F"/></div><div name="w:endnote" w-type="continuationSeparator" w-id="0"><p name="w:p" w-rsidR="005D5C1F" w-rsidRDefault="005D5C1F"/></div><div name="w:endnote" w-type="continuationNotice" w-id="1"><p name="w:p" w-rsidR="005D5C1F" w-rsidRDefault="005D5C1F"/></div></div>`;