
import { Box } from '@mui/material';
import { DialogProps } from '@mui/material/Dialog';
import { SelectChangeEvent } from '@mui/material/Select';
import Chip from '@mui/material/Chip';
import Autocomplete from '@mui/material/Autocomplete';
import TextField from '@mui/material/TextField';
import Stack from '@mui/material/Stack';
import * as React from 'react';

export const TOCConfigDialog = () => {
    const [open, setOpen] = React.useState(false);
    const [headings, setHeadings] = React.useState(top700Headings);

    const handleClickOpen = () => {
        setOpen(true);
    };

    const handleClose = () => {
        setOpen(false);
    };

    const options = headings.filter(item => item.level == null);

    return (
        <React.Fragment>
            <Box>
                {[1, 2, 3, 4, 5, 6].map(level => {
                    return (<Autocomplete
                        style={{ margin: '5px 0' }}
                        key={level}
                        multiple
                        id={`TocHeading${level}`}
                        options={options}
                        getOptionLabel={(option) => option.name}
                        disableCloseOnSelect
                        value={headings.filter(item => item.level == level)}
                        getOptionDisabled={(option) => {
                            console.log(option);
                            return false;
                        }}
                        onChange={(e, value, reason, details) => {
                            console.log(value, reason, details);
                            setHeadings(pre => {
                                let arr = [...pre];
                                let index = arr.findIndex(item => item.name == details?.option.name);
                                switch (reason) {
                                    case 'selectOption':
                                        arr[index + ''].level = reason == "selectOption" ? level : null;
                                        break;
                                    case "clear":
                                        arr = arr.map(item => {
                                            item.level = item.level == level ? null : item.level;
                                            return item;
                                        })
                                        break;
                                    default:
                                        arr[index].level = null;
                                        break;
                                }
                                return arr;
                            });
                        }}
                        renderInput={(params) => (
                            <TextField
                                {...params}
                                variant="outlined"
                                label={`Heading ${level}`}
                                placeholder={`Heading ${level}`}
                            />
                        )}
                    />)
                })}
            </Box>
        </React.Fragment>
    );
}


const top700Headings = [{name: `Normal`, level: null,  id: `Normal`,},
{name: `heading 1`, level: null,  id: `Heading1`,},
{name: `heading 2`, level: null,  id: `Heading2`,},
{name: `heading 3`, level: null,  id: `Heading3`,},
{name: `heading 4`, level: null,  id: `Heading4`,},
{name: `heading 5`, level: null,  id: `Heading5`,},
{name: `heading 6`, level: null,  id: `Heading6`,},
{name: `heading 7`, level: null,  id: `Heading7`,},
{name: `heading 8`, level: null,  id: `Heading8`,},
{name: `heading 9`, level: null,  id: `Heading9`,},
{name: `Default Paragraph Font`, level: null,  id: `DefaultParagraphFont`,},
{name: `Normal Table`, level: null,  id: `TableNormal`,},
{name: `No List`, level: null,  id: `NoList`,},
{name: `Table Grid`, level: null,  id: `TableGrid`,},
{name: `Emphasis`, level: null,  id: `Emphasis`,},
{name: `footnote text`, level: null,  id: `FootnoteText`,},
{name: `Footnote Text Char`, level: null,  id: `FootnoteTextChar`,},
{name: `footnote reference`, level: null,  id: `FootnoteReference`,},
{name: `italic`, level: null,  id: `italic`,},
{name: `Heading 2 Char`, level: null,  id: `Heading2Char`,},
{name: `Heading 3 Char`, level: null,  id: `Heading3Char`,},
{name: `Heading 4 Char`, level: null,  id: `Heading4Char`,},
{name: `Balloon Text Char`, level: null,  id: `BalloonTextChar`,},
{name: `Balloon Text`, level: null,  id: `BalloonText`,},
{name: `Comment Text Char`, level: null,  id: `CommentTextChar`,},
{name: `annotation text`, level: null,  id: `CommentText`,},
{name: `Comment Subject Char`, level: null,  id: `CommentSubjectChar`,},
{name: `annotation subject`, level: null,  id: `CommentSubject`,},
{name: `Header Char`, level: null,  id: `HeaderChar`,},
{name: `header`, level: null,  id: `Header`,},
{name: `Footer Char`, level: null,  id: `FooterChar`,},
{name: `footer`, level: null,  id: `Footer`,},
{name: `Body Text Indent Char`, level: null,  id: `BodyTextIndentChar`,},
{name: `Body Text Indent`, level: null,  id: `BodyTextIndent`,},
{name: `Footnote Characters`, level: null,  id: `FootnoteCharacters`,},
{name: `Strong`, level: null,  id: `Strong`,},
{name: `Footnote Text Char1`, level: null,  id: `FootnoteTextChar1`,},
{name: `Title1`, level: null,  id: `Title1`,},
{name: `srtitle`, level: null,  id: `srtitle`,},
{name: `markedcontent`, level: null,  id: `markedcontent`,},
{name: `verdana`, level: null,  id: `verdana`,},
{name: `Hyperlink`, level: null,  id: `Hyperlink`,},
{name: `fontstyle01`, level: null,  id: `fontstyle01`,},
{name: `Heading 1 Char`, level: null,  id: `Heading1Char`,},
{name: `TOC Heading`, level: null,  id: `TOCHeading`,},
{name: `toc 1`, level: null,  id: `TOC1`,},
{name: `endnote text`, level: null,  id: `EndnoteText`,},
{name: `Endnote Text Char`, level: null,  id: `EndnoteTextChar`,},
{name: `endnote reference`, level: null,  id: `EndnoteReference`,},
{name: `FollowedHyperlink`, level: null,  id: `FollowedHyperlink`,},
{name: `annotation reference`, level: null,  id: `CommentReference`,},
{name: `Heading 5 Char`, level: null,  id: `Heading5Char`,},
{name: `Heading 6 Char`, level: null,  id: `Heading6Char`,},
{name: `Heading 7 Char`, level: null,  id: `Heading7Char`,},
{name: `Heading 8 Char`, level: null,  id: `Heading8Char`,},
{name: `Heading 9 Char`, level: null,  id: `Heading9Char`,},
{name: `BM: Alternate BMH (ABMH)`, level: null,  id: `BMAlternateBMHABMH`,},
{name: `Ad Card: Head (ACH)`, level: null,  id: `AdCardHeadACH`,},
{name: `Ad Card: List (ACL)`, level: null,  id: `AdCardListACL`,},
{name: `Ad Card: Sub Head (ACSH)`, level: null,  id: `AdCardSubHeadACSH`,},
{name: `Ad Card: &quot;With&quot; Line (ACW)`, level: null,  id: `AdCardWithLineACW`,},
{name: `Address (ADD)`, level: null,  id: `AddressADD`,},
{name: `Address: Head (ADDH)`, level: null,  id: `AddressHeadADDH`,},
{name: `FM: Alternate FMH (AFMH)`, level: null,  id: `FMAlternateFMHAFMH`,},
{name: `List: Alphabetical (AL)`, level: null,  id: `ListAlphabeticalAL`,},
{name: `Char Style: Illustrations List Page Number (illpg)`, level: null,  id: `CharStyleIllustrationsListPageNumberillpg`,},
{name: `List: Alphabetical First Item (ALF)`, level: null,  id: `ListAlphabeticalFirstItemALF`,},
{name: `List: Alphabetical Run-in Head (ALH)`, level: null,  id: `ListAlphabeticalRun`,},
{name: `Appendix: List Bulleted (APBL)`, level: null,  id: `AppendixListBulletedAPBL`,},
{name: `Appendix: Text Opener (APCO)`, level: null,  id: `AppendixTextOpenerAPCO`,},
{name: `Appendix: Extract No Indent (APEX)`, level: null,  id: `AppendixExtractNoIndentAPEX`,},
{name: `Appendix: Head (APH)`, level: null,  id: `AppendixHeadAPH`,},
{name: `Appendix: Number (APN)`, level: null,  id: `AppendixNumberAPN`,},
{name: `Appendix: List Numbered (APNL)`, level: null,  id: `AppendixListNumberedAPNL`,},
{name: `Appendix: Head: Sub Head (APSH)`, level: null,  id: `AppendixHeadSubHeadAPSH`,},
{name: `Appendix: Text no indent (APTNI)`, level: null,  id: `AppendixTextnoindentAPTNI`,},
{name: `Appendix: Text (APTX)`, level: null,  id: `AppendixTextAPTX`,},
{name: `Appendix: List Unnumbered (APUL)`, level: null,  id: `AppendixListUnnumberedAPUL`,},
{name: `About the Author: Text (ATA)`, level: null,  id: `AbouttheAuthorTextATA`,},
{name: `About the Author: Head (ATAH)`, level: null,  id: `AbouttheAuthorHeadATAH`,},
{name: `Author Sig (AUSIG)`, level: null,  id: `AuthorSigAUSIG`,},
{name: `Box: List Bulleted (BBL)`, level: null,  id: `BoxListBulletedBBL`,},
{name: `Box: Extract no indent (BEX)`, level: null,  id: `BoxExtractnoindentBEX`,},
{name: `Box: Extract with indent (BEXI)`, level: null,  id: `BoxExtractwithindentBEXI`,},
{name: `Box: Footnote (BFN)`, level: null,  id: `BoxFootnoteBFN`,},
{name: `Box: Head (BH)`, level: null,  id: `BoxHeadBH`,},
{name: `Bibliography: Text (BIB)`, level: null,  id: `BibliographyTextBIB`,},
{name: `Part: Book Number (BKN)`, level: null,  id: `PartBookNumberBKN`,},
{name: `Part: Book Title (BKT)`, level: null,  id: `PartBookTitleBKT`,},
{name: `Part: Book Volume (BKV)`, level: null,  id: `PartBookVolumeBKV`,},
{name: `List: Bulleted (BL)`, level: null,  id: `ListBulletedBL`,},
{name: `List: Bulleted First Item (BLF)`, level: null,  id: `ListBulletedFirstItemBLF`,},
{name: `List: Bulleted run-in head (BLH)`, level: null,  id: `ListBulletedrun`,},
{name: `BM: Author (BMAU)`, level: null,  id: `BMAuthorBMAU`,},
{name: `BM: Text Opener (BMCO)`, level: null,  id: `BMTextOpenerBMCO`,},
{name: `BM: Head (BMH)`, level: null,  id: `BMHeadBMH`,},
{name: `BM: Head 1st Level (BMH1)`, level: null,  id: `BMHead1stLevelBMH1`,},
{name: `BM: Head 2nd Level (BMH2)`, level: null,  id: `BMHead2ndLevelBMH2`,},
{name: `BM: Head: Sub Head (BMSH)`, level: null,  id: `BMHeadSubHeadBMSH`,},
{name: `BM: Text space before (BMSTX)`, level: null,  id: `BMTextspacebeforeBMSTX`,},
{name: `BM: Text no indent (BMTNI)`, level: null,  id: `BMTextnoindentBMTNI`,},
{name: `BM: Text no indent space after (BMTNIS)`, level: null,  id: `BMTextnoindentspaceafterBMTNIS`,},
{name: `BM: Text with indent (BMTX)`, level: null,  id: `BMTextwithindentBMTX`,},
{name: `BM: Text space after (BMTXS)`, level: null,  id: `BMTextspaceafterBMTXS`,},
{name: `Box: Number (BN)`, level: null,  id: `BoxNumberBN`,},
{name: `Box: List Numbered (BNL)`, level: null,  id: `BoxListNumberedBNL`,},
{name: `Text: Bulleted Para (BP)`, level: null,  id: `TextBulletedParaBP`,},
{name: `Text: Bulleted Para: First item (BPF)`, level: null,  id: `TextBulletedParaFirstitemBPF`,},
{name: `Text: Bulleted Para: Subsequent Para (BPTX)`, level: null,  id: `TextBulletedParaSubsequentParaBPTX`,},
{name: `Text: Bulleted Para: with Space After (BPTXS)`, level: null,  id: `TextBulletedParawithSpaceAfterBPTXS`,},
{name: `Box: Sub Head (BSH)`, level: null,  id: `BoxSubHeadBSH`,},
{name: `Box: Source Note (BSN)`, level: null,  id: `BoxSourceNoteBSN`,},
{name: `Box: Text with indent space before (BSTX)`, level: null,  id: `BoxTextwithindentspacebeforeBSTX`,},
{name: `Box: Text no indent (BTNI)`, level: null,  id: `BoxTextnoindentBTNI`,},
{name: `Box: Text Opener (BTO)`, level: null,  id: `BoxTextOpenerBTO`,},
{name: `Box: Text with indent (BTX)`, level: null,  id: `BoxTextwithindentBTX`,},
{name: `Box: Text with indent space after (BTXS)`, level: null,  id: `BoxTextwithindentspaceafterBTXS`,},
{name: `Page Break (PB)`, level: null,  id: `PageBreakPB`,},
{name: `Char Style: Roman (ROMAN)`, level: null,  id: `CharStyleRomanROMAN`,},
{name: `Box: List [i.e. Box UL] (BXL)`, level: null,  id: `BoxListieBoxULBXL`,},
{name: `Callout/Slug (CALL)`, level: null,  id: `CalloutSlugCALL`,},
{name: `Figure: Caption Text (CAP)`, level: null,  id: `FigureCaptionTextCAP`,},
{name: `Chapter: Author (CAU)`, level: null,  id: `ChapterAuthorCAU`,},
{name: `Contents: BM Head (CBMH)`, level: null,  id: `ContentsBMHeadCBMH`,},
{name: `Contents: Chapter Author (CCA)`, level: null,  id: `ContentsChapterAuthorCCA`,},
{name: `Chart: Column Heads (CCH)`, level: null,  id: `ChartColumnHeadsCCH`,},
{name: `Contents: Chapter Number (CCN)`, level: null,  id: `ContentsChapterNumberCCN`,},
{name: `Contents: Chapter Title (CCT)`, level: null,  id: `ContentsChapterTitleCCT`,},
{name: `Chart: Title (CHT)`, level: null,  id: `ChartTitleCHT`,},
{name: `Contents: Front Matter Head (CFMH)`, level: null,  id: `ContentsFrontMatterHeadCFMH`,},
{name: `Contents: Head 1st Level (CH1)`, level: null,  id: `ContentsHead1stLevelCH1`,},
{name: `Contents: Head 2nd Level (CH2)`, level: null,  id: `ContentsHead2ndLevelCH2`,},
{name: `Chart: Body (CHB)`, level: null,  id: `ChartBodyCHB`,},
{name: `Chart: Footnote (CHFN)`, level: null,  id: `ChartFootnoteCHFN`,},
{name: `Chart: Number (CHN)`, level: null,  id: `ChartNumberCHN`,},
{name: `Chart: Source Note (CHSN)`, level: null,  id: `ChartSourceNoteCHSN`,},
{name: `Bibliography: Arch1 (BIBARCH1)`, level: null,  id: `BibliographyArch1BIBARCH1`,},
{name: `List: 2-Column (CL2)`, level: null,  id: `List2`,},
{name: `List: 3-Column (CL3)`, level: null,  id: `List3`,},
{name: `List: 4-Column (CL4)`, level: null,  id: `List4`,},
{name: `List: Column Head (CLH)`, level: null,  id: `ListColumnHeadCLH`,},
{name: `Chapter: Number (CN)`, level: null,  id: `ChapterNumberCN`,},
{name: `Chapter: Number Style (CNN)`, level: null,  id: `ChapterNumberStyleCNN`,},
{name: `Text: Chapter Opener (CO)`, level: null,  id: `TextChapterOpenerCO`,},
{name: `Colophon Text (COL)`, level: null,  id: `ColophonTextCOL`,},
{name: `Text: Computer Code/Type no indent (COM)`, level: null,  id: `TextComputerCodeTypenoindentCOM`,},
{name: `Text: Computer Type with indent (COMI)`, level: null,  id: `TextComputerTypewithindentCOMI`,},
{name: `Text: Computer Code/Type space after (COMS)`, level: null,  id: `TextComputerCodeTypespaceafterCOMS`,},
{name: `Contributors (CON)`, level: null,  id: `ContributorsCON`,},
{name: `Chapter: Title (CT)`, level: null,  id: `ChapterTitleCT`,},
{name: `Chapter: Sub Title (CST)`, level: null,  id: `ChapterSubTitleCST`,},
{name: `Bibliography: Arch2 (BIBARCH2)`, level: null,  id: `BibliographyArch2BIBARCH2`,},
{name: `Text: Chapter Opener space after (COS)`, level: null,  id: `TextChapterOpenerspaceafterCOS`,},
{name: `Bibliography: Arch3 (BIBARCH3)`, level: null,  id: `BibliographyArch3BIBARCH3`,},
{name: `Contents: Part Number (CPN)`, level: null,  id: `ContentsPartNumberCPN`,},
{name: `Contents: Part Title (CPT)`, level: null,  id: `ContentsPartTitleCPT`,},
{name: `Bibliography: Arch4 (BIBARCH4)`, level: null,  id: `BibliographyArch4BIBARCH4`,},
{name: `Copyright Text (CRT)`, level: null,  id: `CopyrightTextCRT`,},
{name: `Chart: Sub Head 1 (CSH1)`, level: null,  id: `ChartSubHead1CSH1`,},
{name: `Chart: Sub Head 2 (CSH2)`, level: null,  id: `ChartSubHead2CSH2`,},
{name: `Char Style: Strikethrough + SmallCaps (STRIKSC)`, level: null,  id: `CharStyleStrikethroughSmallCapsSTRIKSC`,},
{name: `Char Style: Underscore + SmallCaps (USSC)`, level: null,  id: `CharStyleUnderscoreSmallCapsUSSC`,},
{name: `Title Page: Publisher Loc [on title page] (TPPUBLOC)`, level: null,  id: `TitlePagePublisherLocontitlepageTPPUBLOC`,},
{name: `Title Page: ISBN [on title page] (TPISBN)`, level: null,  id: `TitlePageISBNontitlepageTPISBN`,},
{name: `Chapter: Contents Head (COCH)`, level: null,  id: `ChapterContentsHeadCOCH`,},
{name: `Dedication (DED)`, level: null,  id: `DedicationDED`,},
{name: `Section: Contents Head (SOCH)`, level: null,  id: `SectionContentsHeadSOCH`,},
{name: `Dialogue: Text no indent (DIA)`, level: null,  id: `DialogueTextnoindentDIA`,},
{name: `Dialogue: Question (DIAQ)`, level: null,  id: `DialogueQuestionDIAQ`,},
{name: `Dialogue: Text with indent (DIAI)`, level: null,  id: `DialogueTextwithindentDIAI`,},
{name: `Dialogue: Name/Speaker (DIAN)`, level: null,  id: `DialogueNameSpeakerDIAN`,},
{name: `Dateline (DL)`, level: null,  id: `DatelineDL`,},
{name: `Dateline: In Text (DL2)`, level: null,  id: `DatelineInTextDL2`,},
{name: `Dateline: Location (DLL)`, level: null,  id: `DatelineLocationDLL`,},
{name: `Dateline: Time (DLT)`, level: null,  id: `DatelineTimeDLT`,},
{name: `Play/Movie Script: Dramatis Personae/Cast of Characters (DP)`, level: null,  id: `PlayMovieScriptDramatisPersonaeCastofCharactersDP`,},
{name: `Play/Movie Script: Dramatis Personae Head (DPH)`, level: null,  id: `PlayMovieScriptDramatisPersonaeHeadDPH`,},
{name: `Email: Text no indent (EM)`, level: null,  id: `EmailTextnoindentEM`,},
{name: `Email: Text closing (EMC)`, level: null,  id: `EmailTextclosingEMC`,},
{name: `Extract in Email (EMEX)`, level: null,  id: `ExtractinEmailEMEX`,},
{name: `Email: Text with indent (EMI)`, level: null,  id: `EmailTextwithindentEMI`,},
{name: `Email: Text with indent space after (EMIS)`, level: null,  id: `EmailTextwithindentspaceafterEMIS`,},
{name: `Email: Text Opener (EMO)`, level: null,  id: `EmailTextOpenerEMO`,},
{name: `Email: Text no indent space after (EMS)`, level: null,  id: `EmailTextnoindentspaceafterEMS`,},
{name: `Endnote: Head (ENH)`, level: null,  id: `EndnoteHeadENH`,},
{name: `Endnote: Text Para (ENTX)`, level: null,  id: `EndnoteTextParaENTX`,},
{name: `Section: Contents List (SOCL)`, level: null,  id: `SectionContentsListSOCL`,},
{name: `Chapter: Epigraph Text Para (EP)`, level: null,  id: `ChapterEpigraphTextParaEP`,},
{name: `Chapter: Epigraph Author (EPA)`, level: null,  id: `ChapterEpigraphAuthorEPA`,},
{name: `Chapter: Epigraph Credit (EPC)`, level: null,  id: `ChapterEpigraphCreditEPC`,},
{name: `Chapter: Epigraph Text Para with indent (EPI)`, level: null,  id: `ChapterEpigraphTextParawithindentEPI`,},
{name: `Chapter: Epigraph Text Para space after (EPS)`, level: null,  id: `ChapterEpigraphTextParaspaceafterEPS`,},
{name: `Chapter: Epigraph Title (EPT)`, level: null,  id: `ChapterEpigraphTitleEPT`,},
{name: `Chapter: Epigraph Verse prose EP (EPV)`, level: null,  id: `ChapterEpigraphVerseproseEPEPV`,},
{name: `Equation (EQ)`, level: null,  id: `EquationEQ`,},
{name: `Extract: Text no indent (EX)`, level: null,  id: `ExtractTextnoindentEX`,},
{name: `Extract: Author (EXAU)`, level: null,  id: `ExtractAuthorEXAU`,},
{name: `Extract: Centered line-for-line (EXC)`, level: null,  id: `ExtractCenteredline`,},
{name: `Extract: Head (EXH)`, level: null,  id: `ExtractHeadEXH`,},
{name: `Extract: Head 1st level (EXH1)`, level: null,  id: `ExtractHead1stlevelEXH1`,},
{name: `Extract: Text with Indent (EXI)`, level: null,  id: `ExtractTextwithIndentEXI`,},
{name: `Law: Source (LWSR)`, level: null,  id: `LawSourceLWSR`,},
{name: `Extract: Text with Indent space after (EXIS)`, level: null,  id: `ExtractTextwithIndentspaceafterEXIS`,},
{name: `Extract: Ornament (EXORN)`, level: null,  id: `ExtractOrnamentEXORN`,},
{name: `Extract: Ornament 2nd style (EXORN2)`, level: null,  id: `ExtractOrnament2ndstyleEXORN2`,},
{name: `Extract: Text no indent space after (EXS)`, level: null,  id: `ExtractTextnoindentspaceafterEXS`,},
{name: `Extract: Space Break (EXSB)`, level: null,  id: `ExtractSpaceBreakEXSB`,},
{name: `Extract: Source Note (EXSN)`, level: null,  id: `ExtractSourceNoteEXSN`,},
{name: `Extract: Special Extract (EXSP)`, level: null,  id: `ExtractSpecialExtractEXSP`,},
{name: `Law: History (LWHS)`, level: null,  id: `LawHistoryLWHS`,},
{name: `Figure: Text (FIG)`, level: null,  id: `FigureTextFIG`,},
{name: `Figure: Text with indent (FIGI)`, level: null,  id: `FigureTextwithindentFIGI`,},
{name: `Figure: Number (FIGN)`, level: null,  id: `FigureNumberFIGN`,},
{name: `Figure: Source Note (FIGSN)`, level: null,  id: `FigureSourceNoteFIGSN`,},
{name: `Figure: Title (FIGT)`, level: null,  id: `FigureTitleFIGT`,},
{name: `FM: Author (FMAU)`, level: null,  id: `FMAuthorFMAU`,},
{name: `FM: Text Opener (FMCO)`, level: null,  id: `FMTextOpenerFMCO`,},
{name: `FM: Epigraph Only (FMEP)`, level: null,  id: `FMEpigraphOnlyFMEP`,},
{name: `FM: Epigraph Credit (FMEPC)`, level: null,  id: `FMEpigraphCreditFMEPC`,},
{name: `FM: Head (FMH)`, level: null,  id: `FMHeadFMH`,},
{name: `FM: Head 1st Level (FMH1)`, level: null,  id: `FMHead1stLevelFMH1`,},
{name: `FM: Head 2nd Level (FMH2)`, level: null,  id: `FMHead2ndLevelFMH2`,},
{name: `FM: Sub Head (FMSH)`, level: null,  id: `FMSubHeadFMSH`,},
{name: `FM: Text space before (FMSTX)`, level: null,  id: `FMTextspacebeforeFMSTX`,},
{name: `FM: Text no indent (FMTNI)`, level: null,  id: `FMTextnoindentFMTNI`,},
{name: `FM: Text no indent space after (FMTNIS)`, level: null,  id: `FMTextnoindentspaceafterFMTNIS`,},
{name: `FM: Text (FMTX)`, level: null,  id: `FMTextFMTX`,},
{name: `FM: Text space after (FMTXS)`, level: null,  id: `FMTextspaceafterFMTXS`,},
{name: `Footnote: Text First or Only Para (FN)`, level: null,  id: `FootnoteTextFirstorOnlyParaFN`,},
{name: `Footnote: Text Subsequent Para (FNTX)`, level: null,  id: `FootnoteTextSubsequentParaFNTX`,},
{name: `Footnote: Extract (FNEX)`, level: null,  id: `FootnoteExtractFNEX`,},
{name: `Front Sales: Quote (FSQ)`, level: null,  id: `FrontSalesQuoteFSQ`,},
{name: `Front Sales: Quote Credit (FSQC)`, level: null,  id: `FrontSalesQuoteCreditFSQC`,},
{name: `Front Sales: Quote Head (FSQH)`, level: null,  id: `FrontSalesQuoteHeadFSQH`,},
{name: `Front Sales: Quote with para indent (FSQI)`, level: null,  id: `FrontSalesQuotewithparaindentFSQI`,},
{name: `Front Sales: Sub Title (FSST)`, level: null,  id: `FrontSalesSubTitleFSST`,},
{name: `Front Sales: Title (FST)`, level: null,  id: `FrontSalesTitleFST`,},
{name: `Front Sales: Text (FSTX)`, level: null,  id: `FrontSalesTextFSTX`,},
{name: `Glossary Entry (GL)`, level: null,  id: `GlossaryEntryGL`,},
{name: `Glossary Term (GLT)`, level: null,  id: `GlossaryTermGLT`,},
{name: `Head: 1st Level/A Head (H1)`, level: null,  id: `Head1stLevelAHeadH1`,},
{name: `Head: 2nd Level/B Head (H2)`, level: null,  id: `Head2ndLevelBHeadH2`,},
{name: `Head: 3rd Level/C Head (H3)`, level: null,  id: `Head3rdLevelCHeadH3`,},
{name: `Head: 4th Level/D Head (H4)`, level: null,  id: `Head4thLevelDHeadH4`,},
{name: `Head: 5th Head/E Head (H5)`, level: null,  id: `Head5thHeadEHeadH5`,},
{name: `Headnote (HN)`, level: null,  id: `HeadnoteHN`,},
{name: `Headnote with indent (HNI)`, level: null,  id: `HeadnotewithindentHNI`,},
{name: `List of Illustrations (ILL)`, level: null,  id: `ListofIllustrationsILL`,},
{name: `Extract: Inscription or Sign Extract (INS)`, level: null,  id: `ExtractInscriptionorSignExtractINS`,},
{name: `Text: List1 (TXL1)`, level: null,  id: `TextList1TXL1`,},
{name: `Introductory Text Opener i.e. chapter intro that is not text style (INTO)`, level: null,  id: `IntroductoryTextOpeneriechapterintrothatisnottextstyleINTO`,},
{name: `Introductory Text with indent (INTX)`, level: null,  id: `IntroductoryTextwithindentINTX`,},
{name: `Journal Dateline (JRDL)`, level: null,  id: `JournalDatelineJRDL`,},
{name: `Extract in Journal (JREX)`, level: null,  id: `ExtractinJournalJREX`,},
{name: `Journal Text Opener (JRO)`, level: null,  id: `JournalTextOpenerJRO`,},
{name: `Journal Text space before (JRSTX)`, level: null,  id: `JournalTextspacebeforeJRSTX`,},
{name: `Journal Text (JRTX)`, level: null,  id: `JournalTextJRTX`,},
{name: `Journal Text space after (JRTXS)`, level: null,  id: `JournalTextspaceafterJRTXS`,},
{name: `List: Head (LH)`, level: null,  id: `ListHeadLH`,},
{name: `Letter: Text no indent (LT)`, level: null,  id: `LetterTextnoindentLT`,},
{name: `Letter: Address (LTAD)`, level: null,  id: `LetterAddressLTAD`,},
{name: `Letter: Closing (LTCL)`, level: null,  id: `LetterClosingLTCL`,},
{name: `Letter: Dateline (LTDL)`, level: null,  id: `LetterDatelineLTDL`,},
{name: `Letter: Extract in Letter (LTEX)`, level: null,  id: `LetterExtractinLetterLTEX`,},
{name: `Letter: Text with indent (LTI)`, level: null,  id: `LetterTextwithindentLTI`,},
{name: `Letter: Text with indent space after (LTIS)`, level: null,  id: `LetterTextwithindentspaceafterLTIS`,},
{name: `Letter: Post Script (LTPS)`, level: null,  id: `LetterPostScriptLTPS`,},
{name: `Letter: Text no indent space after (LTS)`, level: null,  id: `LetterTextnoindentspaceafterLTS`,},
{name: `Letter: Salutation (LTSA)`, level: null,  id: `LetterSalutationLTSA`,},
{name: `News Article: Dateline (NADL)`, level: null,  id: `NewsArticleDatelineNADL`,},
{name: `News Article: Text No Indent (NAT)`, level: null,  id: `NewsArticleTextNoIndentNAT`,},
{name: `News Article: Text with Indent (NATI)`, level: null,  id: `NewsArticleTextwithIndentNATI`,},
{name: `Notes: Extract no indent (NEX)`, level: null,  id: `NotesExtractnoindentNEX`,},
{name: `Notes: Extract with indent (NEXI)`, level: null,  id: `NotesExtractwithindentNEXI`,},
{name: `List: Numbered (NL)`, level: null,  id: `ListNumberedNL`,},
{name: `List: Numbered Sub List Subsequent Text (NL2TX)`, level: null,  id: `ListNumberedSubListSubsequentTextNL2TX`,},
{name: `List: Numbered First Item (NLF)`, level: null,  id: `ListNumberedFirstItemNLF`,},
{name: `List: Numbered List run-in head (NLH)`, level: null,  id: `ListNumberedListrun`,},
{name: `List: Numbered List Number (NLN)`, level: null,  id: `ListNumberedListNumberNLN`,},
{name: `List: Numbered Subsequent Text (NLTX)`, level: null,  id: `ListNumberedSubsequentTextNLTX`,},
{name: `Notes: Stand-alone Note (NOTE)`, level: null,  id: `NotesStand`,},
{name: `Text: Numbered Para (NP)`, level: null,  id: `TextNumberedParaNP`,},
{name: `Text: Numbered Para First item (NPF)`, level: null,  id: `TextNumberedParaFirstitemNPF`,},
{name: `Text: Numbered Para Subsequent Para (NPTX)`, level: null,  id: `TextNumberedParaSubsequentParaNPTX`,},
{name: `Text: Numbered Paragraph space after (NPTXS)`, level: null,  id: `TextNumberedParagraphspaceafterNPTXS`,},
{name: `Notes: Text No Indent (NTX)`, level: null,  id: `NotesTextNoIndentNTX`,},
{name: `Notes: Text with Indent (NTXI)`, level: null,  id: `NotesTextwithIndentNTXI`,},
{name: `Text: Ornament in Text [usually for Space Break] (ORN)`, level: null,  id: `TextOrnamentinTextusuallyforSpaceBreakORN`,},
{name: `Part: Epigraph (PEP)`, level: null,  id: `PartEpigraphPEP`,},
{name: `Part: Epigraph Credit (PEPC)`, level: null,  id: `PartEpigraphCreditPEPC`,},
{name: `Part: Number (PN)`, level: null,  id: `PartNumberPN`,},
{name: `Part: Number style (PNN)`, level: null,  id: `PartNumberstylePNN`,},
{name: `Part: Text Opener (PO)`, level: null,  id: `PartTextOpenerPO`,},
{name: `Pull Quote (PQ)`, level: null,  id: `PullQuotePQ`,},
{name: `Part: Sub Title (PST)`, level: null,  id: `PartSubTitlePST`,},
{name: `Part: Title (PT)`, level: null,  id: `PartTitlePT`,},
{name: `Part: Dateline (PTDL)`, level: null,  id: `PartDatelinePTDL`,},
{name: `Part: Text no Indent (PTNI)`, level: null,  id: `PartTextnoIndentPTNI`,},
{name: `Part: Text with Indent (PTX)`, level: null,  id: `PartTextwithIndentPTX`,},
{name: `Recipe: By Line (RBY)`, level: null,  id: `RecipeByLineRBY`,},
{name: `Recipe: Directions (RD)`, level: null,  id: `RecipeDirectionsRD`,},
{name: `Recipe: Directions with Indent (RDI)`, level: null,  id: `RecipeDirectionswithIndentRDI`,},
{name: `Reference (REF)`, level: null,  id: `ReferenceREF`,},
{name: `References Head (REFH)`, level: null,  id: `ReferencesHeadREFH`,},
{name: `Text: List2 (TXL2)`, level: null,  id: `TextList2TXL2`,},
{name: `Resources Text (RES)`, level: null,  id: `ResourcesTextRES`,},
{name: `Recipe: Headnote (RHN)`, level: null,  id: `RecipeHeadnoteRHN`,},
{name: `Recipe: Headnote with Indent (RHNI)`, level: null,  id: `RecipeHeadnotewithIndentRHNI`,},
{name: `Recipe: Ingredients (RI)`, level: null,  id: `RecipeIngredientsRI`,},
{name: `Recipe: Ingredients Head (RIH)`, level: null,  id: `RecipeIngredientsHeadRIH`,},
{name: `Recipe: Note (RN)`, level: null,  id: `RecipeNoteRN`,},
{name: `Recipe: Sub Title (RST)`, level: null,  id: `RecipeSubTitleRST`,},
{name: `Recipe: Title (RT)`, level: null,  id: `RecipeTitleRT`,},
{name: `Recipe: Variation (RV)`, level: null,  id: `RecipeVariationRV`,},
{name: `Recipe: Yield (RY)`, level: null,  id: `RecipeYieldRY`,},
{name: `Space Break [aka Section or Text Break] (SB)`, level: null,  id: `SpaceBreakakaSectionorTextBreakSB`,},
{name: `Play/Movie Script: Script Stage Directions (SD)`, level: null,  id: `PlayMovieScriptScriptStageDirectionsSD`,},
{name: `Series Page: List (SERL)`, level: null,  id: `SeriesPageListSERL`,},
{name: `Extract: Text no indent space before (SEX)`, level: null,  id: `ExtractTextnoindentspacebeforeSEX`,},
{name: `Extract: Text with Indent space before (SEXI)`, level: null,  id: `ExtractTextwithIndentspacebeforeSEXI`,},
{name: `Sidebar: Extract No Indent (SIEX)`, level: null,  id: `SidebarExtractNoIndentSIEX`,},
{name: `Sidebar: Extract with Indent (SIEXI)`, level: null,  id: `SidebarExtractwithIndentSIEXI`,},
{name: `Sidebar: Head (SIH)`, level: null,  id: `SidebarHeadSIH`,},
{name: `Sidebar: Text Opener (SIO)`, level: null,  id: `SidebarTextOpenerSIO`,},
{name: `Sidebar: Text with indent space before (SISTX)`, level: null,  id: `SidebarTextwithindentspacebeforeSISTX`,},
{name: `Sidebar: Title (SIT)`, level: null,  id: `SidebarTitleSIT`,},
{name: `Sidebar: Text no indent (SITNI)`, level: null,  id: `SidebarTextnoindentSITNI`,},
{name: `Sidebar: Text with indent (SITX)`, level: null,  id: `SidebarTextwithindentSITX`,},
{name: `Sidebar: Text with indent space after (SITXS)`, level: null,  id: `SidebarTextwithindentspaceafterSITXS`,},
{name: `Letter: Text no indent space before (SLT)`, level: null,  id: `LetterTextnoindentspacebeforeSLT`,},
{name: `Letter: Text with indent space before (SLTI)`, level: null,  id: `LetterTextwithindentspacebeforeSLTI`,},
{name: `Play/Movie Script: Script Text (SP)`, level: null,  id: `PlayMovieScriptScriptTextSP`,},
{name: `Play/Movie Script: Script Head (SPH)`, level: null,  id: `PlayMovieScriptScriptHeadSPH`,},
{name: `Play/Movie Script: Script Speaker (SPK)`, level: null,  id: `PlayMovieScriptScriptSpeakerSPK`,},
{name: `Play/Movie Script: Script Sub Head (SPSH)`, level: null,  id: `PlayMovieScriptScriptSubHeadSPSH`,},
{name: `Play/Movie Script: Script Setting (SS)`, level: null,  id: `PlayMovieScriptScriptSettingSS`,},
{name: `Text: No Indent space before (STNI)`, level: null,  id: `TextNoIndentspacebeforeSTNI`,},
{name: `Text: No Indent space before &amp; after (STNIS)`, level: null,  id: `TextNoIndentspacebeforeafterSTNIS`,},
{name: `Text: Space Before (STX)`, level: null,  id: `TextSpaceBeforeSTX`,},
{name: `Text: Space Before and After (STXS)`, level: null,  id: `TextSpaceBeforeandAfterSTXS`,},
{name: `Head: Summary Head (SUMH)`, level: null,  id: `HeadSummaryHeadSUMH`,},
{name: `Table: Body (TB)`, level: null,  id: `TableBodyTB`,},
{name: `Table: Body Last line [if needed for design] (TBL)`, level: null,  id: `TableBodyLastlineifneededfordesignTBL`,},
{name: `Table: Column Heads (TCH)`, level: null,  id: `TableColumnHeadsTCH`,},
{name: `Text: Epigraph in Body Text (TEP)`, level: null,  id: `TextEpigraphinBodyTextTEP`,},
{name: `Text: Epigraph Credit in body text (TEPC)`, level: null,  id: `TextEpigraphCreditinbodytextTEPC`,},
{name: `Table: Footnote (TFN)`, level: null,  id: `TableFootnoteTFN`,},
{name: `Table: Head 1st Level (TH1)`, level: null,  id: `TableHead1stLevelTH1`,},
{name: `Title`, level: null,  id: `Title`,},
{name: `Title Char`, level: null,  id: `TitleChar`,},
{name: `Table: Number (TN)`, level: null,  id: `TableNumberTN`,},
{name: `Text: List3 (TXL3)`, level: null,  id: `TextList3TXL3`,},
{name: `Text: No Indent space after (TNIS)`, level: null,  id: `TextNoIndentspaceafterTNIS`,},
{name: `Table: Source Note (TSN)`, level: null,  id: `TableSourceNoteTSN`,},
{name: `Table: Title (TT)`, level: null,  id: `TableTitleTT`,},
{name: `Text (TX)`, level: null,  id: `TextTX`,},
{name: `Text: Para Continued (TXCON)`, level: null,  id: `TextParaContinuedTXCON`,},
{name: `Text: Space After (TXS)`, level: null,  id: `TextSpaceAfterTXS`,},
{name: `List: Unnumbered (UL)`, level: null,  id: `ListUnnumberedUL`,},
{name: `List: Unnumbered Sub List (UL2)`, level: null,  id: `ListUnnumberedSubListUL2`,},
{name: `List: Unnumbered Sub List Subsequent Text (UL2TX)`, level: null,  id: `ListUnnumberedSubListSubsequentTextUL2TX`,},
{name: `List: Unnumbered Subsequent Text (ULTX)`, level: null,  id: `ListUnnumberedSubsequentTextULTX`,},
{name: `List: Unnumbered First Item (ULF)`, level: null,  id: `ListUnnumberedFirstItemULF`,},
{name: `Char Style: Url (URL)`, level: null,  id: `CharStyleUrlURL`,},
{name: `Verse/ Poetry (V)`, level: null,  id: `VersePoetryV`,},
{name: `Verse: Dedication (VDED)`, level: null,  id: `VerseDedicationVDED`,},
{name: `Verse: Dateline (VDL)`, level: null,  id: `VerseDatelineVDL`,},
{name: `Verse: Epigraph (VEP)`, level: null,  id: `VerseEpigraphVEP`,},
{name: `Verse: Epigraph Credit (VEPC)`, level: null,  id: `VerseEpigraphCreditVEPC`,},
{name: `Verse: Head 1st Level (VH1)`, level: null,  id: `VerseHead1stLevelVH1`,},
{name: `Verse: Head 2nd Level (VH2)`, level: null,  id: `VerseHead2ndLevelVH2`,},
{name: `Verse: with Indent (VI)`, level: null,  id: `VersewithIndentVI`,},
{name: `Verse: with 2nd Indent (VI2)`, level: null,  id: `Versewith2ndIndentVI2`,},
{name: `Verse: with 3rd Indent (VI3)`, level: null,  id: `Versewith3rdIndentVI3`,},
{name: `Verse: Stanza Break 1st line of a new stanza within V (VSB)`, level: null,  id: `VerseStanzaBreak1stlineofanewstanzawithinVVSB`,},
{name: `Verse: Source Note (VSN)`, level: null,  id: `VerseSourceNoteVSN`,},
{name: `Verse: Sub Title (VST)`, level: null,  id: `VerseSubTitleVST`,},
{name: `Verse: Title (VT)`, level: null,  id: `VerseTitleVT`,},
{name: `Website Resources Text (WRTX)`, level: null,  id: `WebsiteResourcesTextWRTX`,},
{name: `Exercise: Directions (XD)`, level: null,  id: `ExerciseDirectionsXD`,},
{name: `Exercise: Directions with indent (XDI)`, level: null,  id: `ExerciseDirectionswithindentXDI`,},
{name: `Exercise: Head 1st Level (XH1)`, level: null,  id: `ExerciseHead1stLevelXH1`,},
{name: `Exercise: Head 2nd Level (XH2)`, level: null,  id: `ExerciseHead2ndLevelXH2`,},
{name: `Exercise: Number or Crossword Grid Number (XN)`, level: null,  id: `ExerciseNumberorCrosswordGridNumberXN`,},
{name: `Exercise: Title or Crossword Grid Text (XT)`, level: null,  id: `ExerciseTitleorCrosswordGridTextXT`,},
{name: `Exercise: Time (XTM)`, level: null,  id: `ExerciseTimeXTM`,},
{name: `Exercise: Variation (XV)`, level: null,  id: `ExerciseVariationXV`,},
{name: `Char Style: SmallCaps (SC)`, level: null,  id: `CharStyleSmallCapsSC`,},
{name: `Text: List4 (TXL4)`, level: null,  id: `TextList4TXL4`,},
{name: `Char Style: Bold (B)`, level: null,  id: `CharStyleBoldB`,},
{name: `Char Style: Italic (I)`, level: null,  id: `CharStyleItalicI`,},
{name: `Head`, level: null,  id: `Head`,},
{name: `Notes: Letter Text No Indent (NLT)`, level: null,  id: `NotesLetterTextNoIndentNLT`,},
{name: `Char Style: Superscript (SUP)`, level: null,  id: `CharStyleSuperscriptSUP`,},
{name: `Char Style: Subscript (SUB)`, level: null,  id: `CharStyleSubscriptSUB`,},
{name: `Notes: Letter Address (NLTAD)`, level: null,  id: `NotesLetterAddressNLTAD`,},
{name: `Notes: Letter Closing (NLTCL)`, level: null,  id: `NotesLetterClosingNLTCL`,},
{name: `Notes: Letter Dateline (NLTDL)`, level: null,  id: `NotesLetterDatelineNLTDL`,},
{name: `Notes: Extract in Letter (NLTEX)`, level: null,  id: `NotesExtractinLetterNLTEX`,},
{name: `Title Page: Contributors (TPCON)`, level: null,  id: `TitlePageContributorsTPCON`,},
{name: `Text: Alt TX No Indent (ATNI)`, level: null,  id: `TextAltTXNoIndentATNI`,},
{name: `Space Break: 1-Line in Alt text (ATSB1)`, level: null,  id: `SpaceBreak1`,},
{name: `Text: in Alternate Typeface (ATX)`, level: null,  id: `TextinAlternateTypefaceATX`,},
{name: `Text: in 2nd Alternate Typeface (ATX2)`, level: null,  id: `Textin2ndAlternateTypefaceATX2`,},
{name: `Text: List5 (TXL5)`, level: null,  id: `TextList5TXL5`,},
{name: `Appendix: Author (APAU)`, level: null,  id: `AppendixAuthorAPAU`,},
{name: `Appendix: List 2-Column (APCL2)`, level: null,  id: `AppendixList2`,},
{name: `Appendix: List 3-Column (APCL3)`, level: null,  id: `AppendixList3`,},
{name: `Appendix: List 4-Column (APCL4)`, level: null,  id: `AppendixList4`,},
{name: `Appendix: Extract Author (APEXAU)`, level: null,  id: `AppendixExtractAuthorAPEXAU`,},
{name: `Appendix: Extract Centered line-for-line (APEXC)`, level: null,  id: `AppendixExtractCenteredline`,},
{name: `Appendix: Extract first para no indent space above (APEXF)`, level: null,  id: `AppendixExtractfirstparanoindentspaceaboveAPEXF`,},
{name: `Appendix: Extract Head (APEXH)`, level: null,  id: `AppendixExtractHeadAPEXH`,},
{name: `Appendix: Extract Head 1st Level (APEXH1)`, level: null,  id: `AppendixExtractHead1stLevelAPEXH1`,},
{name: `Appendix: Extract with Indent (APEXI)`, level: null,  id: `AppendixExtractwithIndentAPEXI`,},
{name: `Text: List6 (TXL6)`, level: null,  id: `TextList6TXL6`,},
{name: `Appendix: Extract last para indent space below (APEXIL)`, level: null,  id: `AppendixExtractlastparaindentspacebelowAPEXIL`,},
{name: `Appendix: Extract only para indent space above/below (APEXIO)`, level: null,  id: `AppendixExtractonlyparaindentspaceabovebelowAPEXIO`,},
{name: `Appendix: Extract with Indent space after (APEXIS)`, level: null,  id: `AppendixExtractwithIndentspaceafterAPEXIS`,},
{name: `Appendix: Extract last para no indent space below (APEXL)`, level: null,  id: `AppendixExtractlastparanoindentspacebelowAPEXL`,},
{name: `Appendix: Extract only para no indent space above/below (APEXO)`, level: null,  id: `AppendixExtractonlyparanoindentspaceabovebelowAPEXO`,},
{name: `Appendix: Extract no indent space below (APEXS)`, level: null,  id: `AppendixExtractnoindentspacebelowAPEXS`,},
{name: `Appendix: Extract Space Break (APEXSB)`, level: null,  id: `AppendixExtractSpaceBreakAPEXSB`,},
{name: `Appendix: FN (APFN)`, level: null,  id: `AppendixFNAPFN`,},
{name: `Appendix: Head 1st Level (APH1)`, level: null,  id: `AppendixHead1stLevelAPH1`,},
{name: `Appendix: Head 2nd Level (APH2)`, level: null,  id: `AppendixHead2ndLevelAPH2`,},
{name: `Appendix: Head 3rd Level (APH3)`, level: null,  id: `AppendixHead3rdLevelAPH3`,},
{name: `Appendix: Head 4th Level (APH4)`, level: null,  id: `AppendixHead4thLevelAPH4`,},
{name: `Appendix: Head 5th Level (APH5)`, level: null,  id: `AppendixHead5thLevelAPH5`,},
{name: `Appendix: Head Note (APHN)`, level: null,  id: `AppendixHeadNoteAPHN`,},
{name: `Appendix: Letter Text (APLT)`, level: null,  id: `AppendixLetterTextAPLT`,},
{name: `Appendix: Letter Closing (APLTCL)`, level: null,  id: `AppendixLetterClosingAPLTCL`,},
{name: `Appendix: Letter Text with Indent (APLTI)`, level: null,  id: `AppendixLetterTextwithIndentAPLTI`,},
{name: `Appendix: Letter Salutation (APLTSA)`, level: null,  id: `AppendixLetterSalutationAPLTSA`,},
{name: `Appendix: Note Text (APNTX)`, level: null,  id: `AppendixNoteTextAPNTX`,},
{name: `Appendix: Note Text with Indent (APNTXI)`, level: null,  id: `AppendixNoteTextwithIndentAPNTXI`,},
{name: `Appendix: Source Note (APSN)`, level: null,  id: `AppendixSourceNoteAPSN`,},
{name: `Appendix: Text first para following head (APTXF)`, level: null,  id: `AppendixTextfirstparafollowingheadAPTXF`,},
{name: `Appendix: List Unnumbered Sub List (APUL2)`, level: null,  id: `AppendixListUnnumberedSubListAPUL2`,},
{name: `Appendix: Verse Text (APV)`, level: null,  id: `AppendixVerseTextAPV`,},
{name: `Appendix: Verse Stanza Break (APVSB)`, level: null,  id: `AppendixVerseStanzaBreakAPVSB`,},
{name: `BM: Head 3rd Level (BMH3)`, level: null,  id: `BMHead3rdLevelBMH3`,},
{name: `BM: Half Title (BMHT)`, level: null,  id: `BMHalfTitleBMHT`,},
{name: `BM: Ornament (BMORN)`, level: null,  id: `BMOrnamentBMORN`,},
{name: `Bibliography: Annotation (BIBAN)`, level: null,  id: `BibliographyAnnotationBIBAN`,},
{name: `Bibliography: Alternate Text (BIBATX)`, level: null,  id: `BibliographyAlternateTextBIBATX`,},
{name: `Bibliography: List Bulleted (BIBBL)`, level: null,  id: `BibliographyListBulletedBIBBL`,},
{name: `Bibliography: List Numbered (BIBNL)`, level: null,  id: `BibliographyListNumberedBIBNL`,},
{name: `Bibliography: Text Opener no indent (BIBO)`, level: null,  id: `BibliographyTextOpenernoindentBIBO`,},
{name: `Bibliography: Text Opener with indent (BIBOI)`, level: null,  id: `BibliographyTextOpenerwithindentBIBOI`,},
{name: `Bibliography: List Unnumbered (BIBUL)`, level: null,  id: `BibliographyListUnnumberedBIBUL`,},
{name: `Box: Address (BADD)`, level: null,  id: `BoxAddressBADD`,},
{name: `Chapter: Author/Editor Affiliation (CAFF)`, level: null,  id: `ChapterAuthorEditorAffiliationCAFF`,},
{name: `Chapter: Author-Translator (CAUTR)`, level: null,  id: `ChapterAuthor`,},
{name: `Chapter: Editor (CED)`, level: null,  id: `ChapterEditorCED`,},
{name: `Chapter: Contents List (COCL)`, level: null,  id: `ChapterContentsListCOCL`,},
{name: `Chapter: Contents List Page Numbers (coclpg)`, level: null,  id: `ChapterContentsListPageNumberscoclpg`,},
{name: `Chapter: Ornament (CORN)`, level: null,  id: `ChapterOrnamentCORN`,},
{name: `Chronology: Column Heads (CHRCH)`, level: null,  id: `ChronologyColumnHeadsCHRCH`,},
{name: `Chronology: Date (CHRD)`, level: null,  id: `ChronologyDateCHRD`,},
{name: `Chronology: Head 1st Level (CHRH1)`, level: null,  id: `ChronologyHead1stLevelCHRH1`,},
{name: `Chronology: Head 2nd Level (CHRH2)`, level: null,  id: `ChronologyHead2ndLevelCHRH2`,},
{name: `Chronology: Headnote (CHRHN)`, level: null,  id: `ChronologyHeadnoteCHRHN`,},
{name: `Chronology: Text (CHRTX)`, level: null,  id: `ChronologyTextCHRTX`,},
{name: `Chronology: Text Second Para within Chronology Text no para indent (CHRTX1)`, level: null,  id: `ChronologyTextSecondParawithinChronologyTextnoparaindentCHRTX1`,},
{name: `Chronology: Text New Para with indent (CHRTX2)`, level: null,  id: `ChronologyTextNewParawithindentCHRTX2`,},
{name: `Contents: Chapter Sub Title (CCST)`, level: null,  id: `ContentsChapterSubTitleCCST`,},
{name: `Contents: Page Number (CPG)`, level: null,  id: `ContentsPageNumberCPG`,},
{name: `Dictionary: Alpha Divider Head (DADH)`, level: null,  id: `DictionaryAlphaDividerHeadDADH`,},
{name: `Dictionary Entry: Alternate Head (DAEH)`, level: null,  id: `DictionaryEntryAlternateHeadDAEH`,},
{name: `Definition (DDEF)`, level: null,  id: `DefinitionDDEF`,},
{name: `Definition: Source (DDEFS)`, level: null,  id: `DefinitionSourceDDEFS`,},
{name: `Dictionary Entry: Author (DEA)`, level: null,  id: `DictionaryEntryAuthorDEA`,},
{name: `Dictionary Entry: Bibliography (DEBIB)`, level: null,  id: `DictionaryEntryBibliographyDEBIB`,},
{name: `Dictionary: Example Introduced by &quot;e.g.&quot; (DEG)`, level: null,  id: `DictionaryExampleIntroducedbyegDEG`,},
{name: `Dictionary Entry: Head (DEH)`, level: null,  id: `DictionaryEntryHeadDEH`,},
{name: `Dictionary Entry: Head 1st Level (DEH1)`, level: null,  id: `DictionaryEntryHead1stLevelDEH1`,},
{name: `Dictionary Entry: Head 2nd Level (DEH2)`, level: null,  id: `DictionaryEntryHead2ndLevelDEH2`,},
{name: `Dictionary Entry: Head 3rd Level (DEH3)`, level: null,  id: `DictionaryEntryHead3rdLevelDEH3`,},
{name: `Text: Notice (TXNT)`, level: null,  id: `TextNoticeTXNT`,},
{name: `Dictionary Entry (DEN)`, level: null,  id: `DictionaryEntryDEN`,},
{name: `Dictionary: Blind Entry (DENB)`, level: null,  id: `DictionaryBlindEntryDENB`,},
{name: `Dictionary Entry: Notes Head (DENH)`, level: null,  id: `DictionaryEntryNotesHeadDENH`,},
{name: `Dictionary Entry: Notes Text (DENTX)`, level: null,  id: `DictionaryEntryNotesTextDENTX`,},
{name: `Dictionary Entry: Reference Head (DERH)`, level: null,  id: `DictionaryEntryReferenceHeadDERH`,},
{name: `Dictionary Entry: Reference Head run-in [obsolete] (DERHR)`, level: null,  id: `DictionaryEntryReferenceHeadrun`,},
{name: `Dictionary Entry: Reference Sub Head (DERSH)`, level: null,  id: `DictionaryEntryReferenceSubHeadDERSH`,},
{name: `Dictionary Entry: Reference Sub Sub Head (DERSSH)`, level: null,  id: `DictionaryEntryReferenceSubSubHeadDERSSH`,},
{name: `Dictionary Entry: Reference Text (DERTX)`, level: null,  id: `DictionaryEntryReferenceTextDERTX`,},
{name: `Dictionary Entry: Sub Head (DESH)`, level: null,  id: `DictionaryEntrySubHeadDESH`,},
{name: `Text: Notice Head (TXNTH)`, level: null,  id: `TextNoticeHeadTXNTH`,},
{name: `Dictionary: Numbered Definition (DNDEF)`, level: null,  id: `DictionaryNumberedDefinitionDNDEF`,},
{name: `Letter: Head (LTH)`, level: null,  id: `LetterHeadLTH`,},
{name: `Law: Question (LWQ)`, level: null,  id: `LawQuestionLWQ`,},
{name: `Dictionary: See Also Reference (DSEAL)`, level: null,  id: `DictionarySeeAlsoReferenceDSEAL`,},
{name: `Dictionary: See Reference (DSEE)`, level: null,  id: `DictionarySeeReferenceDSEE`,},
{name: `Verse: Example (DVEXA)`, level: null,  id: `VerseExampleDVEXA`,},
{name: `Chapter: Epigraph Second or subsequent epi (EP2)`, level: null,  id: `ChapterEpigraphSecondorsubsequentepiEP2`,},
{name: `Chapter: Epigraph Head (EPH)`, level: null,  id: `ChapterEpigraphHeadEPH`,},
{name: `Equation 2nd style (EQ2)`, level: null,  id: `Equation2ndstyleEQ2`,},
{name: `Equation Number [when Eqs are numbered] (EQN)`, level: null,  id: `EquationNumberwhenEqsarenumberedEQN`,},
{name: `Extract: Text 2nd extract style no indent (EX2)`, level: null,  id: `ExtractText2ndextractstylenoindentEX2`,},
{name: `Extract: List Bulleted (EXBL)`, level: null,  id: `ExtractListBulletedEXBL`,},
{name: `Extract: Text: First Para no indent space above (EXF)`, level: null,  id: `ExtractTextFirstParanoindentspaceaboveEXF`,},
{name: `Extract: Text: Last Para indent space below (EXIL)`, level: null,  id: `ExtractTextLastParaindentspacebelowEXIL`,},
{name: `Extract: Text: Only Para indent space above/below (EXIO)`, level: null,  id: `ExtractTextOnlyParaindentspaceabovebelowEXIO`,},
{name: `Extract: Text: Last Para no indent space below (EXL)`, level: null,  id: `ExtractTextLastParanoindentspacebelowEXL`,},
{name: `Extract: List Numbered (EXNL)`, level: null,  id: `ExtractListNumberedEXNL`,},
{name: `Extract: Text: Only Para no indent space above/below (EXO)`, level: null,  id: `ExtractTextOnlyParanoindentspaceabovebelowEXO`,},
{name: `Extract: List Unnumbered (EXUL)`, level: null,  id: `ExtractListUnnumberedEXUL`,},
{name: `Extract: Verse (EXV)`, level: null,  id: `ExtractVerseEXV`,},
{name: `Letter: Extract Text no indent (EXLT)`, level: null,  id: `LetterExtractTextnoindentEXLT`,},
{name: `Letter: Address in Extract (EXLTAD)`, level: null,  id: `LetterAddressinExtractEXLTAD`,},
{name: `Letter: Closing in Extract (EXLTCL)`, level: null,  id: `LetterClosinginExtractEXLTCL`,},
{name: `Letter: Dateline in Extract (EXLTDL)`, level: null,  id: `LetterDatelineinExtractEXLTDL`,},
{name: `Extract: Extract in Letter (EXLTEX)`, level: null,  id: `ExtractExtractinLetterEXLTEX`,},
{name: `Letter: Extract Text with indent (EXLTI)`, level: null,  id: `LetterExtractTextwithindentEXLTI`,},
{name: `Letter: Extract Text with indent space after (EXLTIS)`, level: null,  id: `LetterExtractTextwithindentspaceafterEXLTIS`,},
{name: `Letter: Post Script in Extract (EXLTPS)`, level: null,  id: `LetterPostScriptinExtractEXLTPS`,},
{name: `Letter: Extract Text no indent space after (EXLTS)`, level: null,  id: `LetterExtractTextnoindentspaceafterEXLTS`,},
{name: `Letter: Salutation in Extract (EXLTSA)`, level: null,  id: `LetterSalutationinExtractEXLTSA`,},
{name: `Letter: Signature in Extract (EXLTSIG)`, level: null,  id: `LetterSignatureinExtractEXLTSIG`,},
{name: `Letter: Extract Text no indent space before (EXSLT)`, level: null,  id: `LetterExtractTextnoindentspacebeforeEXSLT`,},
{name: `Letter: Extract Text with indent space before (EXSLTI)`, level: null,  id: `LetterExtractTextwithindentspacebeforeEXSLTI`,},
{name: `News Article: Byline (NABY)`, level: null,  id: `NewsArticleBylineNABY`,},
{name: `News Article: Byline 2nd line (NABY2)`, level: null,  id: `NewsArticleByline2ndlineNABY2`,},
{name: `News Article: Headline (NAH)`, level: null,  id: `NewsArticleHeadlineNAH`,},
{name: `News Article: Sub Head (NASH)`, level: null,  id: `NewsArticleSubHeadNASH`,},
{name: `Figure: Footnote (FIGFN)`, level: null,  id: `FigureFootnoteFIGFN`,},
{name: `Advisory Board Head (ADVBH)`, level: null,  id: `AdvisoryBoardHeadADVBH`,},
{name: `Advisory Board List (ADVL)`, level: null,  id: `AdvisoryBoardListADVL`,},
{name: `Dedication: Ornament (DEDORN)`, level: null,  id: `DedicationOrnamentDEDORN`,},
{name: `FM: Ornament (FMORN)`, level: null,  id: `FMOrnamentFMORN`,},
{name: `Law: Answer1 (LWA1)`, level: null,  id: `LawAnswer1LWA1`,},
{name: `Index: Main Entry (IX)`, level: null,  id: `IndexMainEntryIX`,},
{name: `Index: Alpha Break Entry (IXA)`, level: null,  id: `IndexAlphaBreakEntryIXA`,},
{name: `Index: Head 1st Level (IXH1)`, level: null,  id: `IndexHead1stLevelIXH1`,},
{name: `Index: Sub Entry (IXS)`, level: null,  id: `IndexSubEntryIXS`,},
{name: `Index: Sub Sub Entry (IXSS)`, level: null,  id: `IndexSubSubEntryIXSS`,},
{name: `Law: Answer2 (LWA2)`, level: null,  id: `LawAnswer2LWA2`,},
{name: `Head: 1st Level Text [if different style than main text] (H1TX)`, level: null,  id: `Head1stLevelTextifdifferentstylethanmaintextH1TX`,},
{name: `Head: 1st Level Text first para (H1TXF)`, level: null,  id: `Head1stLevelTextfirstparaH1TXF`,},
{name: `Index: Sub Sub Entry2 (IXSS2)`, level: null,  id: `IndexSubSubEntry2IXSS2`,},
{name: `Index: Sub Sub Entry3 (IXSS3)`, level: null,  id: `IndexSubSubEntry3IXSS3`,},
{name: `Index: Sub Sub Entry4 (IXSS4)`, level: null,  id: `IndexSubSubEntry4IXSS4`,},
{name: `Index: Sub Sub Entry5 (IXSS5)`, level: null,  id: `IndexSubSubEntry5IXSS5`,},
{name: `Headnote Credit (HNC)`, level: null,  id: `HeadnoteCreditHNC`,},
{name: `Letter: Signature (LTSIG)`, level: null,  id: `LetterSignatureLTSIG`,},
{name: `List: Abbreviations List (ABBL)`, level: null,  id: `ListAbbreviationsListABBL`,},
{name: `List: Alphabetical Sub List (AL2)`, level: null,  id: `ListAlphabeticalSubListAL2`,},
{name: `List: Bulleted Sub List (BL2)`, level: null,  id: `ListBulletedSubListBL2`,},
{name: `List: Bulleted Sub List Subsequent Text (BL2TX)`, level: null,  id: `ListBulletedSubListSubsequentTextBL2TX`,},
{name: `List: Bulleted Subsequent Text (BLTX)`, level: null,  id: `ListBulletedSubsequentTextBLTX`,},
{name: `List: Checklist (CK)`, level: null,  id: `ListChecklistCK`,},
{name: `List: Checklist: Sub List (CK2)`, level: null,  id: `ListChecklistSubListCK2`,},
{name: `List: Checklist: Box (CKBX)`, level: null,  id: `ListChecklistBoxCKBX`,},
{name: `Chapter: Sub Title 2 (CST2)`, level: null,  id: `ChapterSubTitle2CST2`,},
{name: `Text: Numbered Para: Extract (NPEX)`, level: null,  id: `TextNumberedParaExtractNPEX`,},
{name: `Outline Heading (OLH)`, level: null,  id: `OutlineHeadingOLH`,},
{name: `Outline: 1st Level (OL1)`, level: null,  id: `Outline1stLevelOL1`,},
{name: `Outline: 2nd Level (OL2)`, level: null,  id: `Outline2ndLevelOL2`,},
{name: `Outline: 3rd level (OL3)`, level: null,  id: `Outline3rdlevelOL3`,},
{name: `Outline: 4th Level (OL4)`, level: null,  id: `Outline4thLevelOL4`,},
{name: `Answer [in answer key or teacher's guide] (ANS)`, level: null,  id: `AnswerinanswerkeyorteachersguideANS`,},
{name: `Head: 1st Level/A Head (H1A)`, level: null,  id: `Head1stLevelAHeadH1A`,},
{name: `Head: 2nd Level/B Head (H2B)`, level: null,  id: `Head2ndLevelBHeadH2B`,},
{name: `Text: No Indent List1 (TNIL1)`, level: null,  id: `TextNoIndentList1TNIL1`,},
{name: `Menu Item (MENU)`, level: null,  id: `MenuItemMENU`,},
{name: `Menu Head (MENUH)`, level: null,  id: `MenuHeadMENUH`,},
{name: `Proposition (PROP)`, level: null,  id: `PropositionPROP`,},
{name: `Char Style: Symbol Callout (SYM)`, level: null,  id: `CharStyleSymbolCalloutSYM`,},
{name: `Char Style: Underscore (US)`, level: null,  id: `CharStyleUnderscoreUS`,},
{name: `Text: No Indent List2 (TNIL2)`, level: null,  id: `TextNoIndentList2TNIL2`,},
{name: `Text: No Indent List3 (TNIL3)`, level: null,  id: `TextNoIndentList3TNIL3`,},
{name: `Text: No Indent List4 (TNIL4)`, level: null,  id: `TextNoIndentList4TNIL4`,},
{name: `Text: No Indent List5 (TNIL5)`, level: null,  id: `TextNoIndentList5TNIL5`,},
{name: `Char Style: Symbol + Bold Italic (SYMBI)`, level: null,  id: `CharStyleSymbolBoldItalicSYMBI`,},
{name: `Text: No Indent List6 (TNIL6)`, level: null,  id: `TextNoIndentList6TNIL6`,},
{name: `Footnote: List Bulleted (FNBL)`, level: null,  id: `FootnoteListBulletedFNBL`,},
{name: `Footnote: Equation (FNEQ)`, level: null,  id: `FootnoteEquationFNEQ`,},
{name: `Footnote: Extract with para indent (FNEXI)`, level: null,  id: `FootnoteExtractwithparaindentFNEXI`,},
{name: `Footnote: List Numbered (FNNL)`, level: null,  id: `FootnoteListNumberedFNNL`,},
{name: `Footnote: List Unnumbered (FNUL)`, level: null,  id: `FootnoteListUnnumberedFNUL`,},
{name: `Notes: List Bulleted (NBL)`, level: null,  id: `NotesListBulletedNBL`,},
{name: `Notes: Extract: Head (NEXH)`, level: null,  id: `NotesExtractHeadNEXH`,},
{name: `Notes: List Numbered (NNL)`, level: null,  id: `NotesListNumberedNNL`,},
{name: `Notes: List Unnumbered (NUL)`, level: null,  id: `NotesListUnnumberedNUL`,},
{name: `Notes: Verse (NV)`, level: null,  id: `NotesVerseNV`,},
{name: `Notes: Verse Stanza Break (NVSB)`, level: null,  id: `NotesVerseStanzaBreakNVSB`,},
{name: `Notes: Verse Source Note (NVSN)`, level: null,  id: `NotesVerseSourceNoteNVSN`,},
{name: `Part: Epigraph Verse (PEPV)`, level: null,  id: `PartEpigraphVersePEPV`,},
{name: `Part: Ornament (PORN)`, level: null,  id: `PartOrnamentPORN`,},
{name: `Part: Book SubNumber (BKSN)`, level: null,  id: `PartBookSubNumberBKSN`,},
{name: `Part: Volume Number (VOLN)`, level: null,  id: `PartVolumeNumberVOLN`,},
{name: `Part: Volume Title (VOLT)`, level: null,  id: `PartVolumeTitleVOLT`,},
{name: `Permission Acks Text with para indent (PERM)`, level: null,  id: `PermissionAcksTextwithparaindentPERM`,},
{name: `Permission Acks Text with no para indent (PERMF)`, level: null,  id: `PermissionAcksTextwithnoparaindentPERMF`,},
{name: `Document: List Alphabetical (DOCAL)`, level: null,  id: `DocumentListAlphabeticalDOCAL`,},
{name: `Document: Author (DOCAU)`, level: null,  id: `DocumentAuthorDOCAU`,},
{name: `Document: List Bulleted (DOCBL)`, level: null,  id: `DocumentListBulletedDOCBL`,},
{name: `Document: List 2-Column (DOCCL2)`, level: null,  id: `DocumentList2`,},
{name: `Document: List 3-Column (DOCCL3)`, level: null,  id: `DocumentList3`,},
{name: `Document: Date (DOCDA)`, level: null,  id: `DocumentDateDOCDA`,},
{name: `Document: Dialogue (DOCDIA)`, level: null,  id: `DocumentDialogueDOCDIA`,},
{name: `Document: Epigraph (DOCEPI)`, level: null,  id: `DocumentEpigraphDOCEPI`,},
{name: `Document: Epigraph Source (DOCEPS)`, level: null,  id: `DocumentEpigraphSourceDOCEPS`,},
{name: `Document: Extract with para indent (DOCEXI)`, level: null,  id: `DocumentExtractwithparaindentDOCEXI`,},
{name: `Document: Extract no para indent (DOCEX)`, level: null,  id: `DocumentExtractnoparaindentDOCEX`,},
{name: `Document: Title (DOCH)`, level: null,  id: `DocumentTitleDOCH`,},
{name: `Document: Head 1st Level (DOCH1)`, level: null,  id: `DocumentHead1stLevelDOCH1`,},
{name: `Document: Head 2nd Level (DOCH2)`, level: null,  id: `DocumentHead2ndLevelDOCH2`,},
{name: `Document: Head 3rd Level (DOCH3)`, level: null,  id: `DocumentHead3rdLevelDOCH3`,},
{name: `Document: Head 4th Level (DOCH4)`, level: null,  id: `DocumentHead4thLevelDOCH4`,},
{name: `Document: Headnote in Document (DOCHN)`, level: null,  id: `DocumentHeadnoteinDocumentDOCHN`,},
{name: `Document: Headnote in Document with para indent (DOCHNI)`, level: null,  id: `DocumentHeadnoteinDocumentwithparaindentDOCHNI`,},
{name: `Document: Special Head (DOCHSP)`, level: null,  id: `DocumentSpecialHeadDOCHSP`,},
{name: `Document: List Head (DOCLH)`, level: null,  id: `DocumentListHeadDOCLH`,},
{name: `Document: Letter Salutation (DOCLSA)`, level: null,  id: `DocumentLetterSalutationDOCLSA`,},
{name: `Document: Letter Signature (DOCLSIG)`, level: null,  id: `DocumentLetterSignatureDOCLSIG`,},
{name: `Document: Letter Head (DOCLTRH)`, level: null,  id: `DocumentLetterHeadDOCLTRH`,},
{name: `Document: Letter Text (DOCLTX)`, level: null,  id: `DocumentLetterTextDOCLTX`,},
{name: `Document: Multicolumn List Head (DOCMCH)`, level: null,  id: `DocumentMulticolumnListHeadDOCMCH`,},
{name: `Document: Number (DOCN)`, level: null,  id: `DocumentNumberDOCN`,},
{name: `Document: Note Head (DOCN1)`, level: null,  id: `DocumentNoteHeadDOCN1`,},
{name: `Document: List Numbered (DOCNL)`, level: null,  id: `DocumentListNumberedDOCNL`,},
{name: `Document: List Numbered Sub List (DOCNL2)`, level: null,  id: `DocumentListNumberedSubListDOCNL2`,},
{name: `Document: Text Numbered Para (DOCNP)`, level: null,  id: `DocumentTextNumberedParaDOCNP`,},
{name: `Document: Text Numbered Para Cont. (DOCNPTX)`, level: null,  id: `DocumentTextNumberedParaContDOCNPTX`,},
{name: `Document: Note Text (DOCNTX)`, level: null,  id: `DocumentNoteTextDOCNTX`,},
{name: `Document: Outline List Level 1 (DOCOL1)`, level: null,  id: `DocumentOutlineListLevel1DOCOL1`,},
{name: `Document: Outline List Level 2 (DOCOL2)`, level: null,  id: `DocumentOutlineListLevel2DOCOL2`,},
{name: `Document: Outline List Level 3 (DOCOL3)`, level: null,  id: `DocumentOutlineListLevel3DOCOL3`,},
{name: `Document: Source (DOCS)`, level: null,  id: `DocumentSourceDOCS`,},
{name: `Document: Text (DOCTX)`, level: null,  id: `DocumentTextDOCTX`,},
{name: `Document: Text no para indent (DOCTXF)`, level: null,  id: `DocumentTextnoparaindentDOCTXF`,},
{name: `Document: List Unnumbered (DOCUL)`, level: null,  id: `DocumentListUnnumberedDOCUL`,},
{name: `Document: Head 1st Level Verse (DOCVH1)`, level: null,  id: `DocumentHead1stLevelVerseDOCVH1`,},
{name: `Document: Head 2nd Level Verse (DOCVH2)`, level: null,  id: `DocumentHead2ndLevelVerseDOCVH2`,},
{name: `Document: Verse Text (DOCVTX)`, level: null,  id: `DocumentVerseTextDOCVTX`,},
{name: `Pull Quote Credit (PQC)`, level: null,  id: `PullQuoteCreditPQC`,},
{name: `Recipe: Garnish (RG)`, level: null,  id: `RecipeGarnishRG`,},
{name: `Recipe: Head 1st Level/A Head (RH1)`, level: null,  id: `RecipeHead1stLevelAHeadRH1`,},
{name: `Recipe: Head 2nd Level/B Head (RH2)`, level: null,  id: `RecipeHead2ndLevelBHeadRH2`,},
{name: `Recipe: Head 3rd Level/C Head (RH3)`, level: null,  id: `RecipeHead3rdLevelCHeadRH3`,},
{name: `Recipe: Nutritional Information (RNU)`, level: null,  id: `RecipeNutritionalInformationRNU`,},
{name: `Recipe: Variation Head (RVH)`, level: null,  id: `RecipeVariationHeadRVH`,},
{name: `Website Resources List (WRL)`, level: null,  id: `WebsiteResourcesListWRL`,},
{name: `Website Resources URL (WRURL)`, level: null,  id: `WebsiteResourcesURLWRURL`,},
{name: `Website Resources Website name (WRW)`, level: null,  id: `WebsiteResourcesWebsitenameWRW`,},
{name: `Section Number (SECN)`, level: null,  id: `SectionNumberSECN`,},
{name: `Section Sub Title (SECST)`, level: null,  id: `SectionSubTitleSECST`,},
{name: `Section Title (SECT)`, level: null,  id: `SectionTitleSECT`,},
{name: `Series Page: Author (SERAU)`, level: null,  id: `SeriesPageAuthorSERAU`,},
{name: `Series Board Text (SERB)`, level: null,  id: `SeriesBoardTextSERB`,},
{name: `Series Board Head (SERBH)`, level: null,  id: `SeriesBoardHeadSERBH`,},
{name: `Series Page: Contributor Name (SERC)`, level: null,  id: `SeriesPageContributorNameSERC`,},
{name: `Series Page: Contributor Affiliation (SERCAFF)`, level: null,  id: `SeriesPageContributorAffiliationSERCAFF`,},
{name: `Series Page: Editor (SERED)`, level: null,  id: `SeriesPageEditorSERED`,},
{name: `Series Page: Editor Affiliation (SEREDAFF)`, level: null,  id: `SeriesPageEditorAffiliationSEREDAFF`,},
{name: `Series Page: List Head (SERLH)`, level: null,  id: `SeriesPageListHeadSERLH`,},
{name: `Series Number (SERNO)`, level: null,  id: `SeriesNumberSERNO`,},
{name: `Series Page: Sub Head (SERSH)`, level: null,  id: `SeriesPageSubHeadSERSH`,},
{name: `Series Page: Title (SERT)`, level: null,  id: `SeriesPageTitleSERT`,},
{name: `Teaser Opener: Head (TSR1)`, level: null,  id: `TeaserOpenerHeadTSR1`,},
{name: `Teaser Opener: 2nd Level (TSR2)`, level: null,  id: `TeaserOpener2ndLevelTSR2`,},
{name: `Teaser Opener: 3rd Level (TSR3)`, level: null,  id: `TeaserOpener3rdLevelTSR3`,},
{name: `Abstract (ABS)`, level: null,  id: `AbstractABS`,},
{name: `Abstract Head/Sub Head (ABSH)`, level: null,  id: `AbstractHeadSubHeadABSH`,},
{name: `Text: First para following head (TXF)`, level: null,  id: `TextFirstparafollowingheadTXF`,},
{name: `Space Break: 1-Line (SB1)`, level: null,  id: `SpaceBreak1`,},
{name: `Space Break: 1-Line space after (SB1S)`, level: null,  id: `SpaceBreak1`,},
{name: `Space Break: 2-Line (SB2)`, level: null,  id: `SpaceBreak2`,},
{name: `Space Break: 3-Line (SB3)`, level: null,  id: `SpaceBreak3`,},
{name: `Part: Book SubTitle (BKST)`, level: null,  id: `PartBookSubTitleBKST`,},
{name: `Chapter: Sub Chpater Number (SCN)`, level: null,  id: `ChapterSubChpaterNumberSCN`,},
{name: `Text Break [for text following space break usually no indent] (TXB)`, level: null,  id: `TextBreakfortextfollowingspacebreakusuallynoindentTXB`,},
{name: `Chapter: Sub Chapter Title (SCT)`, level: null,  id: `ChapterSubChapterTitleSCT`,},
{name: `Chapter: Sub Number (CSN)`, level: null,  id: `ChapterSubNumberCSN`,},
{name: `Text Break: Opening Style space after (TXBS)`, level: null,  id: `TextBreakOpeningStylespaceafterTXBS`,},
{name: `Title Page: Author (TPAU)`, level: null,  id: `TitlePageAuthorTPAU`,},
{name: `Title Page: Author Affiliation (TPAUAF)`, level: null,  id: `TitlePageAuthorAffiliationTPAUAF`,},
{name: `Title Page: By Line [i.e. &quot;Edited by&quot; &quot;Translated by&quot; etc.] (TPBY)`, level: null,  id: `TitlePageByLineieEditedbyTranslatedbyetcTPBY`,},
{name: `Title Page: Cities [on title page] (TPCIT)`, level: null,  id: `TitlePageCitiesontitlepageTPCIT`,},
{name: `Title Page: Editor (TPED)`, level: null,  id: `TitlePageEditorTPED`,},
{name: `Title Page: Edition (TPEDN)`, level: null,  id: `TitlePageEditionTPEDN`,},
{name: `Title Page: Half Title (TPHT)`, level: null,  id: `TitlePageHalfTitleTPHT`,},
{name: `Title Page: Imprint [on title page] (TPIMP)`, level: null,  id: `TitlePageImprintontitlepageTPIMP`,},
{name: `Title Page: Ornament (TPORN)`, level: null,  id: `TitlePageOrnamentTPORN`,},
{name: `Title Page: Publisher [on title page] (TPPUB)`, level: null,  id: `TitlePagePublisherontitlepageTPPUB`,},
{name: `Title Page: Reading Line (TPRL)`, level: null,  id: `TitlePageReadingLineTPRL`,},
{name: `Title Page: Series Title (TPSER)`, level: null,  id: `TitlePageSeriesTitleTPSER`,},
{name: `Title Page: Series Editor (TPSERED)`, level: null,  id: `TitlePageSeriesEditorTPSERED`,},
{name: `Title Page: Sub Title (TPST)`, level: null,  id: `TitlePageSubTitleTPST`,},
{name: `Title Page: Title (TPT)`, level: null,  id: `TitlePageTitleTPT`,},
{name: `Title Page: Translator Name (TPTRAN)`, level: null,  id: `TitlePageTranslatorNameTPTRAN`,},
{name: `Title Page: Year (TPYR)`, level: null,  id: `TitlePageYearTPYR`,},
{name: `Char Style: Strikethrough (STRIK)`, level: null,  id: `CharStyleStrikethroughSTRIK`,},
{name: `Notes: Letter Text with Indent (NLTI)`, level: null,  id: `NotesLetterTextwithIndentNLTI`,},
{name: `Notes: Letter Text with Indent space after (NLTIS)`, level: null,  id: `NotesLetterTextwithIndentspaceafterNLTIS`,},
{name: `Notes: Letter Post Script (NLTPS)`, level: null,  id: `NotesLetterPostScriptNLTPS`,},
{name: `Notes: Letter Salutation (NLTSA)`, level: null,  id: `NotesLetterSalutationNLTSA`,},
{name: `Notes: Letter Signature (NLTSIG)`, level: null,  id: `NotesLetterSignatureNLTSIG`,},
{name: `Notes: Letter Text No Indent space after (NLTS)`, level: null,  id: `NotesLetterTextNoIndentspaceafterNLTS`,},
{name: `Notes: Letter Text No Indent space before (NSLT)`, level: null,  id: `NotesLetterTextNoIndentspacebeforeNSLT`,},
{name: `Notes: Letter Text with Indent space before (NSLTI)`, level: null,  id: `NotesLetterTextwithIndentspacebeforeNSLTI`,},
{name: `Char Style: Bold Italic (BI)`, level: null,  id: `CharStyleBoldItalicBI`,},
{name: `Char Style: Url + Bold Italic (URLBI)`, level: null,  id: `CharStyleUrlBoldItalicURLBI`,},
{name: `Outline List 2`, level: null,  id: `111111`,},
{name: `Outline List 1`, level: null,  id: `1ai`,},
{name: `Outline List 3`, level: null,  id: `ArticleSection`,},
{name: `Bibliography`, level: null,  id: `Bibliography`,},
{name: `Block Text`, level: null,  id: `BlockText`,},
{name: `Body Text`, level: null,  id: `BodyText`,},
{name: `Body Text Char`, level: null,  id: `BodyTextChar`,},
{name: `Body Text 2`, level: null,  id: `BodyText2`,},
{name: `Body Text 2 Char`, level: null,  id: `BodyText2Char`,},
{name: `Body Text 3`, level: null,  id: `BodyText3`,},
{name: `Body Text 3 Char`, level: null,  id: `BodyText3Char`,},
{name: `Body Text First Indent`, level: null,  id: `BodyTextFirstIndent`,},
{name: `Body Text First Indent Char`, level: null,  id: `BodyTextFirstIndentChar`,},
{name: `Body Text First Indent 2`, level: null,  id: `BodyTextFirstIndent2`,},
{name: `Body Text First Indent 2 Char`, level: null,  id: `BodyTextFirstIndent2Char`,},
{name: `Body Text Indent 2`, level: null,  id: `BodyTextIndent2`,},
{name: `Body Text Indent 2 Char`, level: null,  id: `BodyTextIndent2Char`,},
{name: `Body Text Indent 3`, level: null,  id: `BodyTextIndent3`,},
{name: `Body Text Indent 3 Char`, level: null,  id: `BodyTextIndent3Char`,},
{name: `Book Title`, level: null,  id: `BookTitle`,},
{name: `caption`, level: null,  id: `Caption`,},
{name: `Closing`, level: null,  id: `Closing`,},
{name: `Closing Char`, level: null,  id: `ClosingChar`,},
{name: `Case Study: Head (CASH)`, level: null,  id: `CaseStudyHeadCASH`,},
{name: `Colorful Grid Accent 1`, level: null,  id: `ColorfulGrid`,},
{name: `Colorful Grid Accent 2`, level: null,  id: `ColorfulGrid`,},
{name: `Colorful Grid Accent 3`, level: null,  id: `ColorfulGrid`,},
{name: `Colorful Grid Accent 4`, level: null,  id: `ColorfulGrid`,},
{name: `Colorful Grid Accent 5`, level: null,  id: `ColorfulGrid`,},
{name: `Colorful Grid Accent 6`, level: null,  id: `ColorfulGrid`,},
{name: `Case Study: List Bulleted (CASBL)`, level: null,  id: `CaseStudyListBulletedCASBL`,},
{name: `Colorful List Accent 1`, level: null,  id: `ColorfulList`,},
{name: `Colorful List Accent 2`, level: null,  id: `ColorfulList`,},
{name: `Colorful List Accent 3`, level: null,  id: `ColorfulList`,},
{name: `Colorful List Accent 4`, level: null,  id: `ColorfulList`,},
{name: `Colorful List Accent 5`, level: null,  id: `ColorfulList`,},
{name: `Colorful List Accent 6`, level: null,  id: `ColorfulList`,},
{name: `Case Study: Dialogue (CASDIA)`, level: null,  id: `CaseStudyDialogueCASDIA`,},
{name: `Colorful Shading Accent 1`, level: null,  id: `ColorfulShading`,},
{name: `Colorful Shading Accent 2`, level: null,  id: `ColorfulShading`,},
{name: `Colorful Shading Accent 3`, level: null,  id: `ColorfulShading`,},
{name: `Colorful Shading Accent 4`, level: null,  id: `ColorfulShading`,},
{name: `Colorful Shading Accent 5`, level: null,  id: `ColorfulShading`,},
{name: `Colorful Shading Accent 6`, level: null,  id: `ColorfulShading`,},
{name: `Case Study: Extract (CASEX)`, level: null,  id: `CaseStudyExtractCASEX`,},
{name: `Dark List Accent 1`, level: null,  id: `DarkList`,},
{name: `Dark List Accent 2`, level: null,  id: `DarkList`,},
{name: `Dark List Accent 3`, level: null,  id: `DarkList`,},
{name: `Dark List Accent 4`, level: null,  id: `DarkList`,},
{name: `Dark List Accent 5`, level: null,  id: `DarkList`,},
{name: `Dark List Accent 6`, level: null,  id: `DarkList`,},
{name: `Date`, level: null,  id: `Date`,},
{name: `Date Char`, level: null,  id: `DateChar`,},
{name: `Document Map`, level: null,  id: `DocumentMap`,},
{name: `Document Map Char`, level: null,  id: `DocumentMapChar`,},
{name: `E-mail Signature`, level: null,  id: `E`,},
{name: `E-mail Signature Char`, level: null,  id: `E`,},
{name: `envelope address`, level: null,  id: `EnvelopeAddress`,},
{name: `envelope return`, level: null,  id: `EnvelopeReturn`,},
{name: `HTML Acronym`, level: null,  id: `HTMLAcronym`,},
{name: `HTML Address`, level: null,  id: `HTMLAddress`,},
{name: `HTML Address Char`, level: null,  id: `HTMLAddressChar`,},
{name: `HTML Cite`, level: null,  id: `HTMLCite`,},
{name: `HTML Code`, level: null,  id: `HTMLCode`,},
{name: `HTML Definition`, level: null,  id: `HTMLDefinition`,},
{name: `HTML Keyboard`, level: null,  id: `HTMLKeyboard`,},
{name: `HTML Preformatted`, level: null,  id: `HTMLPreformatted`,},
{name: `HTML Preformatted Char`, level: null,  id: `HTMLPreformattedChar`,},
{name: `HTML Sample`, level: null,  id: `HTMLSample`,},
{name: `HTML Typewriter`, level: null,  id: `HTMLTypewriter`,},
{name: `HTML Variable`, level: null,  id: `HTMLVariable`,},
{name: `index 1`, level: null,  id: `Index1`,},
{name: `index 2`, level: null,  id: `Index2`,},
{name: `index 3`, level: null,  id: `Index3`,},
{name: `index 4`, level: null,  id: `Index4`,},
{name: `index 5`, level: null,  id: `Index5`,},
{name: `index 6`, level: null,  id: `Index6`,},
{name: `index 7`, level: null,  id: `Index7`,},
{name: `index 8`, level: null,  id: `Index8`,},
{name: `index 9`, level: null,  id: `Index9`,},
{name: `index heading`, level: null,  id: `IndexHeading`,},
{name: `Intense Emphasis`, level: null,  id: `IntenseEmphasis`,},
{name: `Intense Quote`, level: null,  id: `IntenseQuote`,},
{name: `Intense Quote Char`, level: null,  id: `IntenseQuoteChar`,},
{name: `Intense Reference`, level: null,  id: `IntenseReference`,},
{name: `Case Study: Question (CASQ)`, level: null,  id: `CaseStudyQuestionCASQ`,},
{name: `Case Study: Text (CASTX)`, level: null,  id: `CaseStudyTextCASTX`,},
{name: `Light Grid Accent 2`, level: null,  id: `LightGrid`,},
{name: `Light Grid Accent 3`, level: null,  id: `LightGrid`,},
{name: `Light Grid Accent 4`, level: null,  id: `LightGrid`,},
{name: `Light Grid Accent 5`, level: null,  id: `LightGrid`,},
{name: `Light Grid Accent 6`, level: null,  id: `LightGrid`,},
{name: `Case Study: Text First Para (CASTXF)`, level: null,  id: `CaseStudyTextFirstParaCASTXF`,},
{name: `Case Study: List Numbered (CASNL)`, level: null,  id: `CaseStudyListNumberedCASNL`,},
{name: `Light List Accent 2`, level: null,  id: `LightList`,},
{name: `Light List Accent 3`, level: null,  id: `LightList`,},
{name: `Light List Accent 4`, level: null,  id: `LightList`,},
{name: `Light List Accent 5`, level: null,  id: `LightList`,},
{name: `Light List Accent 6`, level: null,  id: `LightList`,},
{name: `List: Numbered Sub List (NL2)`, level: null,  id: `ListNumberedSubListNL2`,},
{name: `Style EXBL + Left:  0.5&quot;`, level: null,  id: `StyleEXBLLeft05`,},
{name: `Light Shading Accent 2`, level: null,  id: `LightShading`,},
{name: `Light Shading Accent 3`, level: null,  id: `LightShading`,},
{name: `Light Shading Accent 4`, level: null,  id: `LightShading`,},
{name: `Light Shading Accent 5`, level: null,  id: `LightShading`,},
{name: `Light Shading Accent 6`, level: null,  id: `LightShading`,},
{name: `line number`, level: null,  id: `LineNumber`,},
{name: `List`, level: null,  id: `List`,},
{name: `List 2`, level: null,  id: `List2`,},
{name: `List 3`, level: null,  id: `List3`,},
{name: `List 4`, level: null,  id: `List4`,},
{name: `List 5`, level: null,  id: `List5`,},
{name: `List Bullet`, level: null,  id: `ListBullet`,},
{name: `List Bullet 2`, level: null,  id: `ListBullet2`,},
{name: `List Bullet 3`, level: null,  id: `ListBullet3`,},
{name: `List Bullet 4`, level: null,  id: `ListBullet4`,},
{name: `List Bullet 5`, level: null,  id: `ListBullet5`,},
{name: `List Continue`, level: null,  id: `ListContinue`,},
{name: `List Continue 2`, level: null,  id: `ListContinue2`,},
{name: `List Continue 3`, level: null,  id: `ListContinue3`,},
{name: `List Continue 4`, level: null,  id: `ListContinue4`,},
{name: `List Continue 5`, level: null,  id: `ListContinue5`,},
{name: `List Number`, level: null,  id: `ListNumber`,},
{name: `List Number 2`, level: null,  id: `ListNumber2`,},
{name: `List Number 3`, level: null,  id: `ListNumber3`,},
{name: `List Number 4`, level: null,  id: `ListNumber4`,},
{name: `List Number 5`, level: null,  id: `ListNumber5`,},
{name: `Head: 3rd Level/C Head (H3) Char`, level: null,  id: `Head3rdLevelCHeadH3Char`,},
{name: `macro`, level: null,  id: `MacroText`,},
{name: `Macro Text Char`, level: null,  id: `MacroTextChar`,},
{name: `Char Style: Footnote: Reference/Callout (fnref)`, level: null,  id: `CharStyleFootnoteReferenceCalloutfnref`,},
{name: `Medium Grid 1 Accent 1`, level: null,  id: `MediumGrid1`,},
{name: `Medium Grid 1 Accent 2`, level: null,  id: `MediumGrid1`,},
{name: `Medium Grid 1 Accent 3`, level: null,  id: `MediumGrid1`,},
{name: `Medium Grid 1 Accent 4`, level: null,  id: `MediumGrid1`,},
{name: `Medium Grid 1 Accent 5`, level: null,  id: `MediumGrid1`,},
{name: `Medium Grid 1 Accent 6`, level: null,  id: `MediumGrid1`,},
{name: `Dedication: Author (DEDAU)`, level: null,  id: `DedicationAuthorDEDAU`,},
{name: `Medium Grid 2 Accent 1`, level: null,  id: `MediumGrid2`,},
{name: `Medium Grid 2 Accent 2`, level: null,  id: `MediumGrid2`,},
{name: `Medium Grid 2 Accent 3`, level: null,  id: `MediumGrid2`,},
{name: `Medium Grid 2 Accent 4`, level: null,  id: `MediumGrid2`,},
{name: `Medium Grid 2 Accent 5`, level: null,  id: `MediumGrid2`,},
{name: `Medium Grid 2 Accent 6`, level: null,  id: `MediumGrid2`,},
{name: `Footenote Reference`, level: null,  id: `FootenoteReference`,},
{name: `Medium Grid 3 Accent 1`, level: null,  id: `MediumGrid3`,},
{name: `Medium Grid 3 Accent 2`, level: null,  id: `MediumGrid3`,},
{name: `Medium Grid 3 Accent 3`, level: null,  id: `MediumGrid3`,},
{name: `Medium Grid 3 Accent 4`, level: null,  id: `MediumGrid3`,},
{name: `Medium Grid 3 Accent 5`, level: null,  id: `MediumGrid3`,},
{name: `Medium Grid 3 Accent 6`, level: null,  id: `MediumGrid3`,},
{name: `Char Style: Bold + Superscript (BSUP)`, level: null,  id: `CharStyleBoldSuperscriptBSUP`,},
{name: `Char Style: Bold + Subscript (BSUB)`, level: null,  id: `CharStyleBoldSubscriptBSUB`,},
{name: `Medium List 1 Accent 2`, level: null,  id: `MediumList1`,},
{name: `Medium List 1 Accent 3`, level: null,  id: `MediumList1`,},
{name: `Medium List 1 Accent 4`, level: null,  id: `MediumList1`,},
{name: `Medium List 1 Accent 5`, level: null,  id: `MediumList1`,},
{name: `Medium List 1 Accent 6`, level: null,  id: `MediumList1`,},
{name: `Char Style: Bold + Strikethrough (BSTRIK)`, level: null,  id: `CharStyleBoldStrikethroughBSTRIK`,},
{name: `Medium List 2 Accent 1`, level: null,  id: `MediumList2`,},
{name: `Medium List 2 Accent 2`, level: null,  id: `MediumList2`,},
{name: `Medium List 2 Accent 3`, level: null,  id: `MediumList2`,},
{name: `Medium List 2 Accent 4`, level: null,  id: `MediumList2`,},
{name: `Medium List 2 Accent 5`, level: null,  id: `MediumList2`,},
{name: `Medium List 2 Accent 6`, level: null,  id: `MediumList2`,},
{name: `Char Style: Bold + Underscore (BUS)`, level: null,  id: `CharStyleBoldUnderscoreBUS`,},
{name: `Char Style: Bold + SmallCaps (BSC)`, level: null,  id: `CharStyleBoldSmallCapsBSC`,},
{name: `Medium Shading 1 Accent 2`, level: null,  id: `MediumShading1`,},
{name: `Medium Shading 1 Accent 3`, level: null,  id: `MediumShading1`,},
{name: `Medium Shading 1 Accent 4`, level: null,  id: `MediumShading1`,},
{name: `Medium Shading 1 Accent 5`, level: null,  id: `MediumShading1`,},
{name: `Medium Shading 1 Accent 6`, level: null,  id: `MediumShading1`,},
{name: `Char Style: Bold Italic + Superscript (BISUP)`, level: null,  id: `CharStyleBoldItalicSuperscriptBISUP`,},
{name: `Char Style: Bold Italic + Subscript (BISUB)`, level: null,  id: `CharStyleBoldItalicSubscriptBISUB`,},
{name: `Medium Shading 2 Accent 2`, level: null,  id: `MediumShading2`,},
{name: `Medium Shading 2 Accent 3`, level: null,  id: `MediumShading2`,},
{name: `Medium Shading 2 Accent 4`, level: null,  id: `MediumShading2`,},
{name: `Medium Shading 2 Accent 5`, level: null,  id: `MediumShading2`,},
{name: `Medium Shading 2 Accent 6`, level: null,  id: `MediumShading2`,},
{name: `Message Header`, level: null,  id: `MessageHeader`,},
{name: `Message Header Char`, level: null,  id: `MessageHeaderChar`,},
{name: `No Spacing`, level: null,  id: `NoSpacing`,},
{name: `Normal (Web)`, level: null,  id: `NormalWeb`,},
{name: `Normal Indent`, level: null,  id: `NormalIndent`,},
{name: `Note Heading`, level: null,  id: `NoteHeading`,},
{name: `Note Heading Char`, level: null,  id: `NoteHeadingChar`,},
{name: `page number`, level: null,  id: `PageNumber`,},
{name: `Placeholder Text`, level: null,  id: `PlaceholderText`,},
{name: `Plain Text`, level: null,  id: `PlainText`,},
{name: `Plain Text Char`, level: null,  id: `PlainTextChar`,},
{name: `Quote`, level: null,  id: `Quote`,},
{name: `Quote Char`, level: null,  id: `QuoteChar`,},
{name: `Salutation`, level: null,  id: `Salutation`,},
{name: `Salutation Char`, level: null,  id: `SalutationChar`,},
{name: `Signature`, level: null,  id: `Signature`,},
{name: `Signature Char`, level: null,  id: `SignatureChar`,},
{name: `Subtitle`, level: null,  id: `Subtitle`,},
{name: `Subtitle Char`, level: null,  id: `SubtitleChar`,},
{name: `Subtle Emphasis`, level: null,  id: `SubtleEmphasis`,},
{name: `Head: 4th Level/D Head (H4) Char`, level: null,  id: `Head4thLevelDHeadH4Char`,},
{name: `Table 3D effects 1`, level: null,  id: `Table3Deffects1`,},
{name: `Table 3D effects 2`, level: null,  id: `Table3Deffects2`,},
{name: `Table 3D effects 3`, level: null,  id: `Table3Deffects3`,},
{name: `Table Classic 1`, level: null,  id: `TableClassic1`,},
{name: `Table Classic 2`, level: null,  id: `TableClassic2`,},
{name: `Table Classic 3`, level: null,  id: `TableClassic3`,},
{name: `Table Classic 4`, level: null,  id: `TableClassic4`,},
{name: `Table Colorful 1`, level: null,  id: `TableColorful1`,},
{name: `Table Colorful 2`, level: null,  id: `TableColorful2`,},
{name: `Table Colorful 3`, level: null,  id: `TableColorful3`,},
{name: `Table Columns 1`, level: null,  id: `TableColumns1`,},
{name: `Table Columns 2`, level: null,  id: `TableColumns2`,},
{name: `Table Columns 3`, level: null,  id: `TableColumns3`,},
{name: `Table Columns 4`, level: null,  id: `TableColumns4`,},
{name: `Table Columns 5`, level: null,  id: `TableColumns5`,},
{name: `Table Contemporary`, level: null,  id: `TableContemporary`,},
{name: `Table Elegant`, level: null,  id: `TableElegant`,},
{name: `Table Grid 1`, level: null,  id: `TableGrid1`,},
{name: `Table Grid 2`, level: null,  id: `TableGrid2`,},
{name: `Table Grid 3`, level: null,  id: `TableGrid3`,},
{name: `Table Grid 4`, level: null,  id: `TableGrid4`,},
{name: `Table Grid 5`, level: null,  id: `TableGrid5`,},
{name: `Table Grid 6`, level: null,  id: `TableGrid6`,},
{name: `Table Grid 7`, level: null,  id: `TableGrid7`,},
{name: `Table Grid 8`, level: null,  id: `TableGrid8`,},
{name: `Table List 1`, level: null,  id: `TableList1`,},
{name: `Table List 2`, level: null,  id: `TableList2`,},
{name: `Table List 3`, level: null,  id: `TableList3`,},
{name: `Table List 4`, level: null,  id: `TableList4`,},
{name: `Table List 5`, level: null,  id: `TableList5`,},
{name: `Table List 6`, level: null,  id: `TableList6`,},
{name: `Table List 7`, level: null,  id: `TableList7`,},
{name: `Table List 8`, level: null,  id: `TableList8`,},
{name: `table of authorities`, level: null,  id: `TableofAuthorities`,},
{name: `table of figures`, level: null,  id: `TableofFigures`,},
{name: `Table Professional`, level: null,  id: `TableProfessional`,},
{name: `Table Simple 1`, level: null,  id: `TableSimple1`,},
{name: `Table Simple 2`, level: null,  id: `TableSimple2`,},
{name: `Table Simple 3`, level: null,  id: `TableSimple3`,},
{name: `Table Subtle 1`, level: null,  id: `TableSubtle1`,},
{name: `Table Subtle 2`, level: null,  id: `TableSubtle2`,},
{name: `Table Theme`, level: null,  id: `TableTheme`,},
{name: `Table Web 1`, level: null,  id: `TableWeb1`,},
{name: `Table Web 2`, level: null,  id: `TableWeb2`,},
{name: `Table Web 3`, level: null,  id: `TableWeb3`,},
{name: `toa heading`, level: null,  id: `TOAHeading`,},
{name: `toc 2`, level: null,  id: `TOC2`,},
{name: `toc 3`, level: null,  id: `TOC3`,},
{name: `toc 4`, level: null,  id: `TOC4`,},
{name: `toc 5`, level: null,  id: `TOC5`,},
{name: `toc 6`, level: null,  id: `TOC6`,},
{name: `toc 7`, level: null,  id: `TOC7`,},
{name: `toc 8`, level: null,  id: `TOC8`,},
{name: `toc 9`, level: null,  id: `TOC9`,},
{name: `Char Style: Bold Italic + Strikethrough (BISTRIK)`, level: null,  id: `CharStyleBoldItalicStrikethroughBISTRIK`,},
{name: `Char Style: Bold Italic + SmallCaps (BISC)`, level: null,  id: `CharStyleBoldItalicSmallCapsBISC`,},
{name: `Char Style: Bold Italic + Underscore (BIUS)`, level: null,  id: `CharStyleBoldItalicUnderscoreBIUS`,},
{name: `Char Style: Italic + Superscript (ISUP)`, level: null,  id: `CharStyleItalicSuperscriptISUP`,},
{name: `Char Style: Italic + Subscript (ISUB)`, level: null,  id: `CharStyleItalicSubscriptISUB`,},
{name: `Char Style: Italic + Strikethrough (ISTRIK)`, level: null,  id: `CharStyleItalicStrikethroughISTRIK`,},
{name: `Char Style: Italic + Underscore (IUS)`, level: null,  id: `CharStyleItalicUnderscoreIUS`,},
{name: `Char Style: Italic + SmallCaps (ISC)`, level: null,  id: `CharStyleItalicSmallCapsISC`,},
{name: `Char Style: Url + Bold (URLB)`, level: null,  id: `CharStyleUrlBoldURLB`,},
{name: `Char Style: Url + Italic (URLI)`, level: null,  id: `CharStyleUrlItalicURLI`,},
{name: `Char Style: Url + Underscore (URLU)`, level: null,  id: `CharStyleUrlUnderscoreURLU`,},
{name: `Char Style: Url + Bold + Underscore (URLBU)`, level: null,  id: `CharStyleUrlBoldUnderscoreURLBU`,},
{name: `Char Style: Url + Italic + Underscore (URLIU)`, level: null,  id: `CharStyleUrlItalicUnderscoreURLIU`,},
{name: `Char Style: Url + Bold Italic + Underscore (URLBIU)`, level: null,  id: `CharStyleUrlBoldItalicUnderscoreURLBIU`,},
{name: `Char Style: Symbol + Bold (SYMB)`, level: null,  id: `CharStyleSymbolBoldSYMB`,},
{name: `Char Style: Symbol + Italic (SYMI)`, level: null,  id: `CharStyleSymbolItalicSYMI`,},
{name: `Char Style: Symbol + Underscore (SYMU)`, level: null,  id: `CharStyleSymbolUnderscoreSYMU`,},
{name: `Char Style: Symbol + Bold + Underscore (SYMBU)`, level: null,  id: `CharStyleSymbolBoldUnderscoreSYMBU`,},
{name: `Char Style: Symbol + Italic + Underscore (SYMIU)`, level: null,  id: `CharStyleSymbolItalicUnderscoreSYMIU`,},
{name: `Char Style: Symbol + Bold Italic + Underscore (SYMBIU)`, level: null,  id: `CharStyleSymbolBoldItalicUnderscoreSYMBIU`,},
{name: `Back Ad: Author (BADAU)`, level: null,  id: `BackAdAuthorBADAU`,},
{name: `Back Ad: Book Author (BADBAU)`, level: null,  id: `BackAdBookAuthorBADBAU`,},
{name: `Back Ad: Book Title (BADBT)`, level: null,  id: `BackAdBookTitleBADBT`,},
{name: `Back Ad: Head 1st Level (BADH1)`, level: null,  id: `BackAdHead1stLevelBADH1`,},
{name: `Back Ad: Head 2nd Level (BADH2)`, level: null,  id: `BackAdHead2ndLevelBADH2`,},
{name: `Back Ad: Text (BADTX)`, level: null,  id: `BackAdTextBADTX`,},
{name: `Back Ad: Title (BADT)`, level: null,  id: `BackAdTitleBADT`,},
{name: `Char Style: Endnote: Reference/Callout (enref)`, level: null,  id: `CharStyleEndnoteReferenceCalloutenref`,},
{name: `Sidebar: Head 1st Level/A Head (SIH1)`, level: null,  id: `SidebarHead1stLevelAHeadSIH1`,},
{name: `Sidebar: Author (SIAU)`, level: null,  id: `SidebarAuthorSIAU`,},
{name: `Sidebar: Author Affiliation (SIAUAFF)`, level: null,  id: `SidebarAuthorAffiliationSIAUAFF`,},
{name: `Sidebar: Checklist (SICK)`, level: null,  id: `SidebarChecklistSICK`,},
{name: `Sidebar: Extract Head 1st Level (SIEXH1)`, level: null,  id: `SidebarExtractHead1stLevelSIEXH1`,},
{name: `Sidebar: Extract List Alphabetical/Lettered (SIEXAL)`, level: null,  id: `SidebarExtractListAlphabeticalLetteredSIEXAL`,},
{name: `Sidebar: Extract List Bulleted (SIEXBL)`, level: null,  id: `SidebarExtractListBulletedSIEXBL`,},
{name: `Sidebar: Extract List Numbered (SIEXNL)`, level: null,  id: `SidebarExtractListNumberedSIEXNL`,},
{name: `Sidebar: Extract List Unnumbered (SIEXUL)`, level: null,  id: `SidebarExtractListUnnumberedSIEXUL`,},
{name: `Sidebar: Head 2nd Level/B Head (SIH2)`, level: null,  id: `SidebarHead2ndLevelBHeadSIH2`,},
{name: `Sidebar: Letter Address (SILTAD)`, level: null,  id: `SidebarLetterAddressSILTAD`,},
{name: `Sidebar: Letter Closing (SILTCL)`, level: null,  id: `SidebarLetterClosingSILTCL`,},
{name: `Sidebar: Letter Dateline (SILTDL)`, level: null,  id: `SidebarLetterDatelineSILTDL`,},
{name: `Sidebar: Letter Salutation (SILTSA)`, level: null,  id: `SidebarLetterSalutationSILTSA`,},
{name: `Sidebar: Letter Signature (SILTSIG)`, level: null,  id: `SidebarLetterSignatureSILTSIG`,},
{name: `Sidebar: Letter Text No Indent (SILT)`, level: null,  id: `SidebarLetterTextNoIndentSILT`,},
{name: `Sidebar: Letter Text with Indent (SILTI)`, level: null,  id: `SidebarLetterTextwithIndentSILTI`,},
{name: `Sidebar: List Alphabetical/Lettered (SIAL)`, level: null,  id: `SidebarListAlphabeticalLetteredSIAL`,},
{name: `Sidebar: List Bulleted (SIBL)`, level: null,  id: `SidebarListBulletedSIBL`,},
{name: `Sidebar: List Head (SILH)`, level: null,  id: `SidebarListHeadSILH`,},
{name: `Sidebar: List Numbered (SINL)`, level: null,  id: `SidebarListNumberedSINL`,},
{name: `Sidebar: List Unnumbered (SIUL)`, level: null,  id: `SidebarListUnnumberedSIUL`,},
{name: `Sidebar: Note Head (SINH)`, level: null,  id: `SidebarNoteHeadSINH`,},
{name: `Sidebar: Note Text (SINTX)`, level: null,  id: `SidebarNoteTextSINTX`,},
{name: `Sidebar: Number (SIN)`, level: null,  id: `SidebarNumberSIN`,},
{name: `Sidebar: Source Note (SISN)`, level: null,  id: `SidebarSourceNoteSISN`,},
{name: `Sidebar: Sub Title (SIST)`, level: null,  id: `SidebarSubTitleSIST`,},
{name: `Table: Body List Bulleted (TBBL)`, level: null,  id: `TableBodyListBulletedTBBL`,},
{name: `Table: Body Text Para (TBTX)`, level: null,  id: `TableBodyTextParaTBTX`,},
{name: `Table: Footnote Extract (TFNEX)`, level: null,  id: `TableFootnoteExtractTFNEX`,},
{name: `Table: Footnote List Bulleted (TFNBL)`, level: null,  id: `TableFootnoteListBulletedTFNBL`,},
{name: `Text: No Indent (TNI)`, level: null,  id: `TextNoIndentTNI`,},
{name: `Notes: List Alphabetical/Lettered (NAL)`, level: null,  id: `NotesListAlphabeticalLetteredNAL`,},
{name: `Sidebar: Bibliography/References (SIBIB)`, level: null,  id: `SidebarBibliographyReferencesSIBIB`,},
{name: `Head: 5th Head/E Head (H5) Char`, level: null,  id: `Head5thHeadEHeadH5Char`,},
{name: `Char Style: Head Level1 (H1C)`, level: null,  id: `CharStyleHeadLevel1H1C`,},
{name: `Figure: Credit (CRED)`, level: null,  id: `FigureCreditCRED`,},
{name: `Char Style: Head Level2 (H2C)`, level: null,  id: `CharStyleHeadLevel2H2C`,},
{name: `Char Style: Head Level3 (H3C)`, level: null,  id: `CharStyleHeadLevel3H3C`,},
{name: `Char Style: Head Level4 (H4C)`, level: null,  id: `CharStyleHeadLevel4H4C`,},
{name: `Char Style: Head Level5 (H5C)`, level: null,  id: `CharStyleHeadLevel5H5C`,},
{name: `Char Style: Head Level6 (H6C)`, level: null,  id: `CharStyleHeadLevel6H6C`,},
{name: `Style1`, level: null,  id: `Style1`,},
{name: `Contents: Head 3rd Level (CH3)`, level: null,  id: `ContentsHead3rdLevelCH3`,},
{name: `Contents: Head 4th Level (CH4)`, level: null,  id: `ContentsHead4thLevelCH4`,},
{name: `Contents: Head 5th Level (CH5)`, level: null,  id: `ContentsHead5thLevelCH5`,},
{name: `Contents: Head 6th Level (CH6)`, level: null,  id: `ContentsHead6thLevelCH6`,},
{name: `List: List1 (L1)`, level: null,  id: `ListList1L1`,},
{name: `List: List2 (L2)`, level: null,  id: `ListList2L2`,},
{name: `List: List3 (L3)`, level: null,  id: `ListList3L3`,},
{name: `List: List4 (L4)`, level: null,  id: `ListList4L4`,},
{name: `List: List5 (L5)`, level: null,  id: `ListList5L5`,},
{name: `List: List6 (L6)`, level: null,  id: `ListList6L6`,},
{name: `Law: Index Entry1 (IX1)`, level: null,  id: `LawIndexEntry1IX1`,},
{name: `Law: Index Entry2 (IX2)`, level: null,  id: `LawIndexEntry2IX2`,},
{name: `Law: Index Entry3 (IX3)`, level: null,  id: `LawIndexEntry3IX3`,},
{name: `Law: Index Entry4 (IX4)`, level: null,  id: `LawIndexEntry4IX4`,},
{name: `Law: Index Entry5 (IX5)`, level: null,  id: `LawIndexEntry5IX5`,},
{name: `Law: Index Entry6 (IX6)`, level: null,  id: `LawIndexEntry6IX6`,},
{name: `Notes: UnNumbered Text No Indent (UNN)`, level: null,  id: `NotesUnNumberedTextNoIndentUNN`,},
{name: `Notes: UnNumbered Text with Indent (UNNI)`, level: null,  id: `NotesUnNumberedTextwithIndentUNNI`,},
{name: `Chapter: Key Terms (KT)`, level: null,  id: `ChapterKeyTermsKT`,},
{name: `Chapter: Key Terms Head (KTH)`, level: null,  id: `ChapterKeyTermsHeadKTH`,},
{name: `Case Study: Head1 (CASH1)`, level: null,  id: `CaseStudyHead1CASH1`,},
{name: `Case Study: Head2 (CASH2)`, level: null,  id: `CaseStudyHead2CASH2`,},
{name: `Case Study: Head3 (CASH3)`, level: null,  id: `CaseStudyHead3CASH3`,},
{name: `Case Study: Head4 (CASH4)`, level: null,  id: `CaseStudyHead4CASH4`,},
{name: `Case Study: Head5 (CASH5)`, level: null,  id: `CaseStudyHead5CASH5`,},
{name: `Document: Dateline (DOCDL)`, level: null,  id: `DocumentDatelineDOCDL`,},
{name: `Endnote: Extract (ENEX)`, level: null,  id: `EndnoteExtractENEX`,},
{name: `Endnote: Extract Head (ENEXH)`, level: null,  id: `EndnoteExtractHeadENEXH`,},
{name: `Endnote: Extract Source Note (ENEXSN)`, level: null,  id: `EndnoteExtractSourceNoteENEXSN`,},
{name: `Endnote: Extract with Indent (ENEXI)`, level: null,  id: `EndnoteExtractwithIndentENEXI`,},
{name: `Endnote: Head Author Head (ENCAU)`, level: null,  id: `EndnoteHeadAuthorHeadENCAU`,},
{name: `Endnote: Verse (ENV)`, level: null,  id: `EndnoteVerseENV`,},
{name: `Endnote: Verse Source Note (ENVSN)`, level: null,  id: `EndnoteVerseSourceNoteENVSN`,},
{name: `Interview: Answer (INTA)`, level: null,  id: `InterviewAnswerINTA`,},
{name: `Interview: Question (INTQ)`, level: null,  id: `InterviewQuestionINTQ`,},
{name: `Procedure: Head (POH)`, level: null,  id: `ProcedureHeadPOH`,},
{name: `Procedure: Step (POST)`, level: null,  id: `ProcedureStepPOST`,},
{name: `Procedure: Sub Head (POSH)`, level: null,  id: `ProcedureSubHeadPOSH`,},
{name: `Procedure: Text (POTX)`, level: null,  id: `ProcedureTextPOTX`,},
{name: `Procedure: Text No Indent (POTNI)`, level: null,  id: `ProcedureTextNoIndentPOTNI`,},
{name: `Reference Title (REFT)`, level: null,  id: `ReferenceTitleREFT`,},
{name: `Rule (RULE)`, level: null,  id: `RuleRULE`,},
{name: `Part: Author (PA)`, level: null,  id: `PartAuthorPA`,},
{name: `Head: Special Head (HSPH)`, level: null,  id: `HeadSpecialHeadHSPH`,},
{name: `Head: Special Head Level 2 (HSPH2)`, level: null,  id: `HeadSpecialHeadLevel2HSPH2`,},
{name: `Document: Head 1st Level Space above (DOCH1F)`, level: null,  id: `DocumentHead1stLevelSpaceaboveDOCH1F`,},
{name: `Document: Title above Space (DOCHF)`, level: null,  id: `DocumentTitleaboveSpaceDOCHF`,},
{name: `Extract: Dialogue (EXDIA)`, level: null,  id: `ExtractDialogueEXDIA`,},
{name: `Chapter: End of Chapter Subhead (ECSH)`, level: null,  id: `ChapterEndofChapterSubheadECSH`,},
{name: `Endnote: Sub Head (ENSH)`, level: null,  id: `EndnoteSubHeadENSH`,},
{name: `BM: Title (BMT)`, level: null,  id: `BMTitleBMT`,},
{name: `BM: SubTitle (BMST)`, level: null,  id: `BMSubTitleBMST`,},
{name: `Sidebar: Footnote (SIFN)`, level: null,  id: `SidebarFootnoteSIFN`,},
{name: `Char Style: Language-1 (LANG1)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-1 Bold (LANG1-B)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-1 Bold Italic (LANG1-BI)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-1 Italic (LANG1-I)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-2 (LANG2)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-2 Bold (LANG2-B)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-2 Bold Italic (LANG2-BI)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-2 Italic (LANG2-I)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-3 (LANG3)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-3 Bold (LANG3-B)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-3 Bold Italic (LANG3-BI)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-3 Italic (LANG3-I)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-4 (LANG4)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-4 Bold (LANG4-B)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-4 Bold Italic (LANG4-BI)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-4 Italic (LANG4-I)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-5 (LANG5)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-5 Bold (LANG5-B)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-5 Bold Italic (LANG5-BI)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-5 Italic (LANG5-I)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-6 (LANG6)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-6 Bold (LANG6-B)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-6 Bold Italic (LANG-BI)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-6 Italic (LANG6-I)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-7 (LANG7)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-7 Bold (LANG7-B)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-7 Bold Italic (LANG7-BI)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-7 Italic (LANG7-I)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-8 (LANG8)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-8 Bold (LANG8-B)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-8 Bold Italic (LANG8-BI)`, level: null,  id: `CharStyleLanguage`,},
{name: `Char Style: Language-8 Italic (LANG8-I)`, level: null,  id: `CharStyleLanguage`,},];